### ISSUE TITLE
Improve install process

### ISSUE THREAD

**Issue by bbkane** [a-h/templ#10]
Hello,

I'm trying to install `templ`, and I have a couple of suggestions to make it easier to install:

# Include an "Install" section in README.md

I might have missed a section, but I didn't see how to install `templ` from the README, only how to build locally. It can be a really short section, but also really helpful :) If you'd like inspiration, I'm pretty happy with how [my Install section](https://github.com/bbkane/kvcrutch/blob/master/README.md#install) turned out.

# Make `templ` easily `go install`able

I was able to install `templ` with `go install github.com/a-h/templ/cmd`, but because the last directory is named `cmd`, the binary is now named `cmd` on my system. If you moved it to `github.com/a-h/templ/cmd/templ`, I would be able to run `go install github.com/a-h/templ/cmd/templ` and end up with a binary named `templ`

# Use GoReleaser's HomeBrew support

GoReleaser can support [generating Homebrew formulas](https://goreleaser.com/customization/homebrew/) so MacOS users can do something like `brew install a-h/tap/templ` if they wish. They won't even need `GOPATH/bin` in their `PATH`, because Homebrew will manage paths. I use this functionality for a little CLI I wrote and it works well once you get the tap repo and access token build- very much set up and forget. Feel free to take inspiration from my [`.goreleaser.yml`](https://github.com/bbkane/kvcrutch/blob/master/.goreleaser.yml)

**Comment by bbkane** [comment]
I'm happy to make PRs to effect these changes should you decide you'd like some/all of them implemented.

**Comment by a-h** [comment]
Brilliant, thanks a lot for thinking about this.

For some reason, I didn't think of the `go install` workflow at all for installation. I really like your idea of moving the command so the executable name is correct when you run `go install`.

Since `templ` is a tool for Go programmers, users will definitely have Go installed, I think that would make homebrew unnecessary, what do you think?

Reading through your docs, I noticed that you've written that using `go install` means that you lose version information. I was a bit worried about this, because I thought it would be hard to chase down bugs if people couldn't say what version of templ they were using, so I did a bit of research.

It turns out that you can get the Go module version at runtime using https://pkg.go.dev/runtime/debug#ReadBuildInfo and also from the Go command line tools using the `go version -m <binary>` command (https://golang.org/ref/mod#go-version-m). This might not the case in all Go version, but it's definitely the case in Go 1.16.

I've updated templ to get the Go module version instead of using `ldFlags` passed in by the goreleaser build in this commit: 

https://github.com/a-h/templ/commit/4e12d5286467f1fa3477baf86d71630f25678ceb

So, the `go install` command can install the latest version, or a specific tag:

```
go install github.com/a-h/templ/cmd@latest
# or
go install github.com/a-h/templ/cmd@v0.0.95
```

I've pushed a tag (but not pushed a release for v0.0.95), so you can try out installing: `go install github.com/a-h/templ/cmd@v0.0.95` - you should get `cmd` added to your path, and if you run `cmd --version` you should see `v0.0.95`.

What do you think about the approach of using `go install` in this way?

If you're willing to move the command, and raise PRs that detail installation instructions using `go install`, I'd be delighted to merge them. 😁 If not, let me know and I'll get around to it.

**Comment by bbkane** [comment]
I wasn't aware of the `ReadBuildInfo` method for getting the version - I'll be modifying my own CLI to make that work.

I've added an entry on my todo list to make the `cmd` -> `cmd/templ` move and add an "Install" section to the README when I'm not on work time :)

In regards to HomeBrew, I prefer HomeBrew commands to manage the lifecycle of all the applications it supports. I'm more used to HomeBrew commands than `go install` commands, and GoReleaser makes it really easy to set up CI/CD to generate and auoto-update the formula. As you said, however, `templ` is useless without `go` and `go install` is not exactly difficult to use. At the end of the day, I just want a binary named `templ` in my `PATH`.

**Comment by bbkane** [comment]
Created https://github.com/a-h/templ/pull/11

**Comment by a-h** [comment]
Thanks for your contribution, much appreciated. It's all merged in!
