### ISSUE TITLE
VS Code plugin: changelog tab

### ISSUE THREAD

**Issue by PaluMacil** [a-h/templ#101]
Currently https://github.com/a-h/templ-vscode/blob/main/CHANGELOG.md is just the initial template. It would be great to have details because while I'm trying to be an early adopter of templ, a friend I collaborate with frequently feels that the language server and/or IDE plugin is just not anywhere close to being truly helpful at this point. Separately, I would love to see a Goland plugin, but in the near term, I think seeing more detail on the changelog will let people see if there is interesting progress to take a look at. Currently I am using Goland with no assistance at all, but looking at the state today reveals to me that a **lot** of progress was made since I last used this plugin a few weeks ago.

**Comment by a-h** [comment]
Thanks, most of the work is actually in the LSP (https://github.com/a-h/templ/tree/main/cmd/templ/lspcmd). I've done a lot of work on the internals - I rebuilt the parser to take advantage of Go generics and reduce the code volume, and rewrote the internal document representation (the previous version was a source of many bugs). There's also a really useful internal viewer in the LSP now - it can start a web server you can use to visualise its internal state which made it much easier to track down weirdness.

I'm thinking of adding some realtime logging visualisation in there too, because reading the JSON logs is quite tricky.

The VS Code plugin basically just passes commands and data to/from the LSP program and includes a syntax highlighting file. There's no interesting code in it at all.

I expected the changelog of the VS Code plugin to be updated automatically by the VS Code tooling using the git commit history, I didn't spot that it wasn't updated. I expect there's a tool that does this, and the job is just to add it to the npm scripts.

wrt to a Goland plugin, I expect that Goland is similar to VS Code, in that it's a case of providing an appropriate syntax highlighting file, and a way of configuring / starting the LSP.

My current focus is around the LSP, when I'm really happy with that, then I could take a look at the Goland side.

**Comment by a-h** [comment]
OK, I've updated the project to use standard-version to automate the creation of CHANGELOG.md in https://github.com/a-h/templ-vscode/commit/6b01a220b79b5a0970b06132e4389bcd9b2ce359#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

This is now reflected in the VS Code Extension page: https://marketplace.visualstudio.com/items/a-h.templ/changelog

I've created https://github.com/a-h/templ/issues/127 to track the Goland IDE support - they released LSP support recently, so it looks pretty straightforward to implement. I think the syntax highlighting uses the same format at VS Code too.

Probably best to carry that conversation on over there. 😁
