### ISSUE TITLE
Getting help from AI: Context document

### ISSUE THREAD

**Issue by Yacobolo** [a-h/templ#1016]
Chat GPT generally has a hard time assisting with templ.

**Reason**: Not enough code examples on the internet.

**Solution**: Give it context
A text file can be made which can be fed to the AI so it knows exactly how templ works.

Heres an example from fasthtml:

[FASTHTML Docs](https://docs.fastht.ml/)
[/llms-ctx.txt](https://docs.fastht.ml/llms-ctx.txt)
```
Getting help from AI
Because FastHTML is newer than most LLMs, AI systems like Cursor, ChatGPT, Claude, and Copilot won’t give useful answers about it. To fix that problem, we’ve provided an LLM-friendly guide that teaches them how to use FastHTML. To use it, add this link for your AI helper to use:

This example is in a format based on recommendations from Anthropic for use with [Claude Projects](https://support.anthropic.com/en/articles/9517075-what-are-projects). This works so well that we’ve actually found that Claude can provide even better information than our own documentation! For instance, read through [this annotated Claude chat](https://gist.github.com/jph00/9559b0a563f6a370029bec1d1cc97b74) for some great getting-started information, entirely generated from a project using the above text file as context.

If you use Cursor, type @doc then choose “Add new doc”, and use the /llms-ctx.txt link above. The context file is auto-generated from our [llms.txt](https://llmstxt.org/) (our proposed standard for providing AI-friendly information)—you can generate alternative versions suitable for other models as needed.
```

**Comment by a-h** [comment]
Thanks for your thoughts.

Is your proposal to merge all the docs into a single markdown file because it makes it easier for a specific LLM agent (Cursor) to consume?

templ already has markdown based documentation: https://github.com/a-h/templ/tree/main/docs/docs, so all that would be required would be copy `index.md` to be `llms.txt` because it's an overview of templ, then to `cat` all the other files together as `llms-ctx.txt` and dump them in the root directory of `templ.guide` (or somewhere else).

Thoughts:
 - Why is the file extension .txt when it's a markdown file? https://github.com/AnswerDotAI/llms-txt/issues/4
 - Why not `.well-known`? https://github.com/AnswerDotAI/llms-txt/issues/2
 - Is anyone other than FastHTML actually doing this? Seems like FastHTML is the creator of this proposal - I'm thinking that maybe no-one else is considering doing this, so it might be pointless.
 - Why hasn't any of the feedback raised (e.g. issues 2 and 4) been adopted. Thinking that the proposal might already be dead.
 - Why not suggest changes to Docusaurus and other documentation generators, so we don't have to maintain a process here?
 - Can't cursor be pointed at the raw docs Markdown directory in Github?

**Comment by joerdav** [comment]
I think rather than adhering to a standard that seems to be in flux at the moment, maybe a quick win is to just produce a single file that contains the documentation at templ.guide/llms.md

I'm currently using a copilot chat plugin for neovim, which does support adding a local directory as context. Or supports adding a URL for a single file. I've tested this by pointing it at relevant pages of the docs for what I'm asking.

Agree that this would be a great feature for docusaurus, is there an easy way for us to aggregate md files into one for now?

**Comment by Yacobolo** [comment]
@a-h FastHTML is created by Jeremy Howard who is big on AI and creator of the [fastai lib](https://github.com/fastai/fastai) I agree with @joerdav to create the single llms.md, i think it could solve the pain point some of us have with using llms with templ. It would have to be tested how effective it is.

**Comment by joerdav** [comment]
My testing of single docs pages was a bit dissapointing....
Maybe a md with mor examples would help.
```
 🤔 ───

#url:https://templ.guide/syntax-and-usage/elements

I want to write a html component using a-h/templ syntax. The component should take a title and description and render a card that displays the information.

 🤖 ───

Sure, here's an example of a HTML component using a-h/templ syntax that takes a title and description and renders a card:

````templ
// card.templ
package main

templ component Card(title string, description string) {
  <div class="card">
    <h2>{title}</h2>
    <p>{description}</p>
  </div>
}
````
```

**Comment by a-h** [comment]
Simplest way to combine everything is to run cat in the `./docs` directory and create the static output.

```
find docs | grep '.*md$' | xargs cat > ./static/llms.md
```

**Comment by joerdav** [comment]
Tested that out, and works great with LLMs that don't quite understand templ yet! I'll issue a PR, I added a step into the npm scripts.

**Comment by joerdav** [comment]
Before merging, maybe (paradoxically) I should add a page in the docs that outlines the existence of this asset.

**Comment by a-h** [comment]
Ha, yes, ideally, we'd have a page that describes how to use the `llms.md` with various editors. I can't actually find any decent documentation on doing that.

I've put a placeholder documentation page in, and raised an issue on https://github.com/AnswerDotAI/llms-txt/issues/29

I think that it would be helpful for the llms-txt project to handle it.

**Comment by Yacobolo** [comment]
Hey guys much appriciation. This works like a charm, just what i needed! 👍
