### ISSUE TITLE
generator: allow go code statements in templates

### ISSUE THREAD

**Issue by delaneyj** [a-h/templ#109]
In quick template you can add go vote anywhere in template using current scope.  Doesn't appear to be possible here.  Am I missing something?

**Comment by a-h** [comment]
Do you have an example of what you're trying to do? You mean to do something like `<div data-{dataName}="{value} other">`?

If so, templ doesn't allow for that, it's trying to make sure you're outputting valid HTML. The templ parser constructs an object model and then generates code from that, whereas IIRC, QuickTemplate doesn't have that step, which is what makes it harder to create an LSP for.

templ has context-aware escaping based on Google's SafeHTML. It applies security escaping for dynamic values based on whether the attribute is a script or CSS class, so it currently needs to know (at compile time) what the attribute name is going to be. If you start a constant attribute value, no interpolation happens inside that.

**Comment by joerdav** [comment]
I think what is being referenced here is similar to the Raw function in templ, this is what quick template provides as documentation for this keyword:

```{% code
// arbitrary Go code may be embedded here!
type FooArg struct {
    Name string
    Age int
}
%}```

**Comment by joerdav** [comment]
On reviewing this it is not similar to the Raw function. But there is a reason templ doesn't have an equivelant.

In quicktemplate the "root" file is a template, so you have to deliniate where Go code is:

```
{% import "foo/bar" %}

{% func PrintPage(p Page) %}
    <html>
        <head><title>{%= p.Title() %}</title></head>
        <body>
            <div>{%= p.Body("foo", 42) %}</div>
            <div>{%= p.Footer() %}</div>
        </body>
    </html>
{% endfunc %}

{% code
type BasePage struct {
    TitleStr string
    FooterStr string
}
%}
```

Whereas in templ the file is more like templates within Go code, so the `code` keyword is not required:

```go
import "foo/bar"

templ PrintPage(p Page) {
    <html>
        <head><title>{%= p.Title() %}</title></head>
        <body>
            <div>{%= p.Body("foo", 42) %}</div>
            <div>{%= p.Footer() %}</div>
        </body>
    </html>
}

type BasePage struct {
    TitleStr string
    FooterStr string
}
```


Shout if I missed the point @delaneyj !

**Comment by joerdav** [comment]
Understood! It could be argued that a template is doing too much if that is needed. But whether that is something templ should be opinionated on is another story!

But just to be clear you are asking for something such as the following to be valid:

```go
templ PrintPage(p Page) {
	{ x := computeTitle(p) }
    <html>
        <head><title>{ x }</title></head>
        <body>
            <div>{ p.Body("foo", 42) }</div>
            <div>{ p.Footer() }</div>
        </body>
    </html>
}
```

Essentially allow go _statements_ to be interpolated within a component, rather than just go _expressions_.

Just a note on this before I forget, if we did implement this, we would need to think about how this works with shadowing templ generated variables. In the generated go code of a template we have variables such as "ctx", "err", "w", "var_1", "var_2" that would maybe conflict with a variables created in a statement. We may have to switch to randomly generated names.

**Comment by delaneyj** [comment]
Yes, the thing is, compiled templates "are just go code" so having code scoped is very valuable.  I use heavily in quicktemplate for complicated stuff like auto-generated naming or lookups in a cfg to a shortened name.

**Comment by mgkpete** [comment]
it's worth noting that simple assignments are already possible, albeit seemingly somewhat inadvertently.  It's a hack but it is possible by doing the assignment within an if statement, for example:

```
templ PrintPage(p Page) {
    if x := computeTitle(p); true {
        <html>
            <head><title>{ x }</title></head>
            <body>
                <div>{ p.Body("foo", 42) }</div>
                <div>{ p.Footer() }</div>
            </body>
        </html>
    }
}
```

As a more general point I think wider support of more language features would be a good thing, as the inline nature of if/range/switch control statements makes it feel like other things should work. I got caught out trying to use continue/break only to find they weren't supported. Although, I also feel the current syntax doesn't lend itself to that goal, mainly due to the way if/range/switch statements aren't guarded by braces (unlike expressions) which might lead to issues differentiating them from template content outside of html tags?

**Comment by jonerer** [comment]
+1 on this. In my example I'm doing a DB lookup, which I don't want to repeat. So I'd like to be able to do something like

templ teamInviteComponent() {
	{ invites := GetMyPendingInvites(ctx) }
	if len(invites) > 0 {
		<div>You have { len(invites) } pending invites</div>
               ... (more code to loop here)
	}
}

**Comment by a-h** [comment]
Thanks for the input on this folks. I was thinking that people wouldn't do expensive operations like database lookups etc. directly in their templates, and that templates would be pure functions that take in an input view model / "Props" type, hence not much need for inline variables etc.

For example...

```go
type Handler struct {
  DB *DB
}

func (h Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
  var m InviteComponentViewModel
  m.Invites, err := h.DB.GetInvites(getUserIDFromContext(r.Context()))
  if err != nil {
     //TODO: Log error.
    m.ErrorMessage = "Failed to load invites, please try again"
  }
  teamInviteComponentModel(m).Render(r.Context(), w)
}

type InviteComponentViewModel struct {
  Invites []Invite
  ErrorMessage string
}

templ teamInviteComponent(model InviteComponentViewModel) {
	if len(model.Invites) > 0 {
		<div>You have { len(model.Invites) } pending invites</div>
               ... (more code to loop here)
	}
        if props.ErrorMessage != "" {
              ... (display error message)
        }
}
```

I didn't actually document that thinking anywhere though, and I don't think templ should limit how people want to work.

I think the `{{ // Go Code }}` syntax would work well and would be fairly straightforward to implement. Most of the templ variables that make up the generated code are prefixed with `templ`, except for `var_1` names, and those should/could be renamed to start with templ like the others, e.g. `templ_var_1`.

**Comment by joerdav** [comment]
I can definitely see the value in this for making templates look cleaner, or reusing the result of a function.

But I also agree, making a database call from a template seems like an anti-pattern to me. For testing purposes it's much purer if you have all the information before you start to render.

**Comment by delaneyj** [comment]
Counter point, making extra structs and allocations when it's all just Go functions (especially in the same scope and call stack) seems like an anti-pattern.

**Comment by joerdav** [comment]
Maybe there is a good use for it, but a database call embeded in the rendering of a template is a scary concept to me.

Especially since in the current state of things we can't pass errors up from a template.

**Comment by vikstrous** [comment]
The high level idea makes sense to me, but I wonder if this can work more like jsx? I don't write jsx normally, so I might be wrong, but I think jsx lets you write normal JavaScript as long as you return an html element. It would be cool if that could also work here. I'm not sure if jsx allows for early return. Anyway, my thinking is "jsx looks nice and they seem to have this figured out, so maybe templ can work the same way"

**Comment by joerdav** [comment]
@vikstrous, so I think what you are proposing is that templ functions should have explicit returns rather than implicit? You would be able to write Go code inside a templ function until the point of the `return` keyword?

Using my previous example:
```
templ PrintPage(p Page) {
	x := computeTitle(p)
    return (
	    <html>
	        <head><title>{ x }</title></head>
	        <body>
	            <div>{ p.Body("foo", 42) }</div>
	            <div>{ p.Footer() }</div>
	        </body>
	    </html>
	)
}
```

I think ergonomically it makes sense, as something _is_ being returned from a templ function.

Although, this would involve the leap of going from our naive Go parsing strategy* to fully parsing Go code.

It would also involve allowing component variables in my opinion, as if you can return a template you should be able to instantiate a variable with one too:

```
templ PrintPage(p Page) {
	x := computeTitle(p)
	body := (
		<body>
			<div>{ p.Body("foo", 42) }</div>
	        <div>{ p.Footer() }</div>
		</body>
	)
    return (
	    <html>
	        <head><title>{ x }</title></head>
	        @body
	    </html>
	)
}
```

*the only parsing we do is of control statements (if/for/switch), beyond that we just trust that anything between curly braces is Go code.

**Comment by vikstrous2** [comment]
Yeah, I think that's my proposal. I'm realizing now how such a seemingly small change could require a very different architecture. Maybe this is worth exploring in a separate github issue from this one? I'm guessing that a change like this is very dependent on your ability to extend gopls to support this.

From gopls' perspective, this is a similar problem to highlighting sql text or other embedded formats. I noticed that there's a need to highlight javascript even within templ... so this is definitely a deep rabbit hole, but I do think that if all these languages can somehow coexist and be parsed correctly in the same file, the developer experience for templ could be 10x better than alternatives in Go.

**Comment by joerdav** [comment]
@vikstrous2 agree this is a separate issue worth discussing. Currently with gopls we proxy the templ lsp through to gopls, I believe even with this new architecture it would be the same thing, a case of mapping to the generated go code and relaying gopls messages back to the client and mapping the file positions accordingly. 

So it's definitely possible, just a big undertaking.

**Comment by a-h** [comment]
Just leaving this thought here around having an equivalent of React's context object (https://react.dev/learn/passing-data-deeply-with-context) - as per this conversation: https://www.reddit.com/r/golang/comments/1755wh9/comment/k4y5d2i/?utm_source=share&utm_medium=web2x&context=3

If we implement "arbitrary code" in Go templates then we can use Go's built-in context to pass things deep through the stack without "prop drilling".

I'm not 100% convinced on the use of context in React. I tend to the explicitness and ease of understanding of drilling. If there's a choice between a compile time failure, and a runtime failure, I always prefer compile time, since that's not going to affect my customers.

Like here, the right thing to do in this example is to use a string argument to `Child`, so you can't forget to add something to the context, and end up causing a runtime panic.

```
templ Parent(ctx context.Context, name string) {
  {{ ctx = context.WithValue(ctx, "key", name) }}
  <div>
    @child(ctx){}
  </div>
}

templ Child(ctx context.Context) {
  <div>
    <button value={ ctx.Value("key") } />
  </div>
}
```

I do like the idea of dropping the implicit return. However, I do think it would mean essentially forking the Go parser, which I think might be too much of a maintenance burden for templ at the moment. If I was full time on it, maybe...

**Comment by joerdav** [comment]
@a-h now that we are using the go parser for go expressions I wonder if the`{{...}}` syntax is needed? Maybe we are able to differentiate expressions vs statements and declarations so that the following is possible:

```templ
templ t() {
  {
    getVal := func() string {
      return ""
    }
  }
  { myval := getVal() }
  <div>{ myval }</div>
}
```

I haven't yet written a PoC so there may be a reason that this isn't possible?

**Comment by a-h** [comment]
See https://github.com/a-h/templ/pull/713

I think the docs would need an update. In particular, I'm concerned about people trying to do things like `for` loops inside this syntax, and getting very confused as to why they can't, e.g.:

```templ
{{
for x := 0; x < 123; x ++ {
  <div>{ strconv.Itoa(x) }</div>
}
}}
```

In terms of the risk of the new feature, was wondering about whether to feature-flag it to allow people to use it (at their own, significant risk), while we work out kinks.

**Comment by a-h** [comment]
Am interested in how the LSP behaves, and I guess this would have ripple effects through the editor plugins.

**Comment by joerdav** [comment]
Feature flag is a good shout. Do we want to follow the go approach of having an experiment env var which enables it?

The docs are on the todo list, good point on making it clear its a go only context not templ.

In terms of the LSP it seems to work as expected, I added to the sourcemap. We will need to update all of our grammars: treesitter, textmate, psi

**Comment by AlexanderArvidsson** [comment]
> Feature flag is a good shout. Do we want to follow the go approach of having an experiment env var which enables it?
> 
> The docs are on the todo list, good point on making it clear its a go only context not templ.
> 
> In terms of the LSP it seems to work as expected, I added to the sourcemap. We will need to update all of our grammars: treesitter, textmate, psi

@joerdav Personally, I'd eventually want the flag to exist within the repository, not as an environment variable. But as long as this is considered experimental, following the Go approach as an env flag is ok. However, once this (and possibly many other optional features) are stable, a config file may be a good approach.

**Comment by joerdav** [comment]
I think post-experiment the flag would be removed entirely rather than being immortalized in a config file.

We've thus far avoided a config file because we believe it to be counter productive to support a lot of config. And we haven't yet seen a use that warrants changing that approach, and I don't think short lived feature flags is it either.
