### ISSUE TITLE
Allow Component into Style / Script

### ISSUE THREAD

**Issue by benjiro29** [a-h/templ#120]
I am currently trying to include automatically CSS/JS into the HTML headers.

```
  templ Layout(css2 templ.Component, js2 templ.Component) {
	  <html>
		  <head>
                      <style type="text/css"> {! css2 } </style>
                      <script> {! js2 } </script>
		  </head>
		  <body>
  ...
  }
```

css2/js2 are unescaped and safe code coming from external files during compile/first run.

Style and Script tag do not allow including html/script. I understand that this is not desired to prevent people from including script tags inside of posts etc. But script / style tags inside the header need to be considered safe from outside attacks.

Why do i want to do it this way? By keeping the css/js code in separate files, makes it easier to use the appropriate linting / code formatters and other VSC helper function (that do not work in templ templates). And on compile/first run that code gets combined/cleaned/stripped ...

Why not simply use links... Longer render times as first page request, with a reduce first render time of the page. And as a SPA, there is no follow-up requests for any header content anyway.

For the most part i am very happy with templ but sometimes the safety barriers are really in the way of actually developing content.

**Comment by benjiro29** [comment]
A alternative solution is to unescape the entire component and include the script or style tag directly.

 Closing this for now...

**Comment by a-h** [comment]
Did you spot the https://templ.guide/core-concepts/components/#code-only-components in the docs?

It's possible to create something like this in a Go file.

```go
import _ "embed"

//go:embed header.js
var scriptInHeader string

func unsafeScript(s string) templ.Component {
    return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
        io.WriteString(w, "<script type=\"javascript\">\n"+s+"\n</script>")
        return nil
    })
}
```

Then use it in a templ file with the `@unsafeScript` syntax.

```
@unsafeScript(scriptInHeader)
```

Not sure if that helps?

I haven't included it in the runtime portion of templ because the "Safe HTML" concept is to make it hard to do the wrong thing by providing a sensible API, but it's possible that it's just too annoying for people who know what they're doing, and maybe adding a `templ.UnsanitizedScript` or `templ.UnsanitizedStyle` function is sensible?
