### ISSUE TITLE
CSS expressions middleware wants type templ.ComponentCSSClass & not templ.CSSClass

### ISSUE THREAD

**Issue by topi314** [a-h/templ#150]
I tried to use https://templ.guide/syntax-and-usage/css-style-management/#css-middleware to combine all my css expressions into a single stylesheet, but templ generates css expressions with the return type of `templ.CSSClass`
example:

```go
css ErrorDetails() {
	text-align: start;
}
```
->
```go
func ErrorDetails() templ.CSSClass {
	var templCSSBuilder strings.Builder
	templCSSBuilder.WriteString(`text-align:start;`)
	templCSSID := templ.CSSID(`ErrorDetails`, templCSSBuilder.String())
	return templ.ComponentCSSClass{
		ID:    templCSSID,
		Class: templ.SafeCSS(`.` + templCSSID + `{` + templCSSBuilder.String() + `}`),
	}
}
```

now I can't pass these classes into `templ.NewCSSHandler(ErrorDetails())` since it wants `...templ.ComponentCSSClass`

from what I can tell this requires a simple fix in here:
https://github.com/a-h/templ/blame/b6358024ebd0c83257331b6f08053d4a946a2b76/generator/generator.go#L178

**Comment by a-h** [comment]
Hi @topi314 - thanks a lot for looking into this, and sorry for the inconvenience there.

It seems there was a missing spot in the testing. The unit test covered the behaviour, but there was no integration of real usage.

I tried your PR, but it broke the snapshot tests since it resulted in CSS not being rendered. Rather than change the generated type that's output, I tried to stick with `CSSClass` and use a type check in the middleware code instead. Since `CSSClass` is more general (interface type), it shouldn't break any code that's used the variadic method of adding values, but it would break code where people have used an array of `ComponentCSSClass` items since Go can't convert between the two.

I've also added a unit test that describes the expected behaviour so there isn't a future regression. 

https://github.com/a-h/templ/pull/152

I'll sleep on this change before comitting, since it affects the public API of templ. 😁 

Does that work for you?

**Comment by topi314** [comment]
sounds good to me!
thanks for the quick response

**Comment by topi314** [comment]
I would love for CSS support to be expanded beyond classes, it's annoying to manually bundle or import a dozen of stylesheets. Pehaps in component `<style>` tags could also be added to the middleware?

**Comment by a-h** [comment]
This is now fixed in https://github.com/a-h/templ/commit/712895e501895bbee8301de155f7443c05403da6 and https://github.com/a-h/templ/commit/2ebb638c53b528e905c78ecd37377eb373b1aa8a

I think that bundling stylesheets might be out of scope for templ. I don't know what your workflow for manual bundling looks like, but esbuild (also written in Go) can bundle stylesheets https://esbuild.github.io/content-types/#css

To be able to extract CSS class elements from within templ components to add them to a global stylesheet would require a modification to the generator to generate a new method on a component that makes all `<style>` elements in the component available. The `<style>` elements are picked up by the templ parser, and the generator currently just writes Go code that renders the string out.

One way to handle that would be that  the generator could write out another function alongside the component, e.g. (`<ComponentName>CSS(ctx context.Context, w io.Writer) error`?) that writes out the contents of all `<style>` elements in the component _and_ renders any referenced templ CSS components (only if required). Then, it would be possible to call `NewCSSMiddleware(httpRoutes, MyComponentCSS)` and register all the CSS in one go.

Is that what you were thinking?

**Comment by topi314** [comment]
> I think that bundling stylesheets might be out of scope for templ. I don't know what your workflow for manual bundling looks like, but esbuild (also written in Go) can bundle stylesheets [esbuild.github.io/content-types/#css](https://esbuild.github.io/content-types/#css)

I actually just switched over to use esbuild within my go code since it has a go api


> Is that what you were thinking?
this is about what I was thinking, rendering the `<style>` tags into it's own `<ComponentName>CSS` function would allow me to get fully rid of `esbuild` for css. this sounds awesome👍🏻
I also use it to bundle the javascript rn

**Comment by topi314** [comment]
since the original issue has been fixed in https://github.com/a-h/templ/releases/tag/v0.2.364 I'm gonna close this as completed

some component like css support with the middleware would still be nice
thanks!
