### ISSUE TITLE
Variable names defined in templates can clash with variables in compiled output

### ISSUE THREAD

**Issue by nics** [a-h/templ#169]
This template fragment generates invalid output because the `err` variable name clashes with the generated variable name:

```
if err := validationErrors.Get("name"); e != nil {
  <label>{ err.Error() }</label> 
}
```

Generates:

```
if err := errs.Get("name"); e != nil {
    _, err = templBuffer.WriteString(...)
   if err != nil {
	return err
  }
}
```

Other variable names used like `ctx` and even `var_1` have the same drawbacks.

Quicktemplate generates var names like `qb422016` that avoid these clashes.

**Comment by a-h** [comment]
Thanks, good point. And relatively straightforward to resolve.

I was already thinking that all templ variables should start with a templ_ prefix. Could also use templ_7e31_ as a prefix for extra random.

**Comment by a-h** [comment]
I've made it so that all templ variables start with `templ` in that PR. All  the tests pass once the templates are regenerated.

Could use a review of that @joerdav / @nics - since it's a potentially breaking change.

**Comment by nics** [comment]
Hi @a-h just tried it out and works fine for me. The change will only break things if people were relying on the behaviour of the bug I think?

**Comment by a-h** [comment]
It would also break people's code if they were using the context (`ctx`) variable, or the `w` variable. 

For example, it could be that people decided to do something like this:

```go
templ Example(s string) {
  if result, ok := db.GetResult(ctx, "1"); ok {
     { result.Name }
  }
}
```

Or...

```go
templ Example(s string) {
  if ok := sideEffectingFunctionThatWritesTo(w); !ok {
     <div>There was a problem</div>
  }
}
```

That's why I'm still not 100% sure about the changes to the `ctx` and `w` variables. I think the change to the `err` variable, and the other internal `templ*` variables is safe.

The questions I want to answer before merge are:

* Are we (as templ users), supposed to know that the `ctx` and `w` variables exist, and... should we use them?
* If `ctx` doesn't exist, where should we get a context from?

**Comment by nics** [comment]
Personally I wouldn't expect _any_ internal variable to be exposed to the writer of a template, those are just the internal mechanics. If someone needs a context, they can just pass it explicitly and exposing the writer breaks all the guardrails of templ.

**Comment by joerdav** [comment]
I agree, it's all internals. The user has access to pass variables in at compose time, so could pass their own context, but really what happens at render time and how it happens is up to templ. 

If someone needs to customize how the writer and context is used at render time they can always implement templ.Component if they need to do something out of the ordinary and not catered for.

**Comment by jonerer** [comment]
I'm confused by this change. How can I access things in the context? Or how am I supposed to solve these kinds of problems with shared concerns now?

I thought since templ doesn't like me to do error-prone things, or things with statements, in the template, I should perform them before-hand and put them in the context.

Things like:

- I have a project management site. It typically want to show all projects pertaining to a user on the left hand side. So the controller would have to have put that in the context beforehand.
- The user can get invited to another team, so pending invites are loaded in a middleware, and each page will let it get rendered
- Basically anything like a ["flash message"](https://www.rubyguides.com/2019/11/rails-flash-messages/)

This is how I've solved the sidebar and case now. How should I solve it if the template can't access the context? 

I don't really udnerstand what @joerdav means by "they can implement templ.Component if they need to do something out of the ordinary and not catered for." Does that mean I can't do it in a template, but instead have to write the components as custom go code?

```
func ShowItemHandler(c *gin.Context) {
        [... snip ...]
	item, err := db.Db.GetItemById(dbCtx, id_num)
        [... snip ...]

	loadSidebarContext(c, shared.SidebarHighlight{
		Kind:      "project",
		ProjectID: item.ProjectID,
	})

	views.ShowItemPage(item).Render(c.Request.Context(), c.Writer)
}
```

And the item page like

```
templ ShowItemPage(item db.Item) {
	@layout("item") {
            ... showing the item here ...
        }
```

```
templ layout(name string) {
	<html class="h-full">
		<body class="h-full bg-gray-800 text-gray-300">
		<div>
			@sidebarComponent()
		</div>
		<div>
			<h1>{ name }</h1>
			@teamInviteComponent()
			{ children... }
		</div>
		</body>
	</html>
}
```

And the sidebar uses a lot of context from middleware and others:

```
templ sidebarComponent() {
		<div class="flex flex-col h-full">
			<div>
				<div>
					if GetSidebarContext(ctx).IsHome() {
						->
					}
					<a href="/">Home</a>
				</div>
				<div>
					if GetSidebarContext(ctx).IsProjects() {
						->
					}
					<a href={ templ.URL(fmt.Sprintf("/teams/%d/projects", shared.CurActiveTeamId(ctx))) }>Projects</a>
				</div>
				<div>
					for _, project := range GetSidebarContext(ctx).Projects {
						<div>
							<div>
								if GetSidebarContext(ctx).IsProject(project.ID) {
									->
								}
								<a href={ templ.URL(fmt.Sprintf("/projects/%d", project.ID)) }>{ project.Name }</a>
							</div>
						</div>
					}
				</div>
				<div><a href="/teams">Teams</a></div>
				if GetSidebarContext(ctx).Team != nil {
					<div>
						if GetSidebarContext(ctx).IsTeam(GetSidebarContext(ctx).Team.ID) {
							->
						}
						<a href={ templ.URL(fmt.Sprintf("/teams/%d", shared.CurActiveTeamId(ctx))) }>{ GetSidebarContext(ctx).Team.Name }</a>
					</div>
				}
			</div>
			<div class="flex-1"></div>
			<div>Current User: { shared.CurUserName(ctx) }<a href="/logout">Logout</a></div>
		</div>
}
```

**Comment by a-h** [comment]
Firstly, sorry that we broke your project with this change. It's annoying when stuff like that happens, so I especially appreciate your detailed message and time you spent to contribute your thoughts.

I think your solution of having a strongly typed "view model" / "site state" structure, and passing it through the stack is solid, and that's likely what I'd go with, because it provides compile time checks for all values.

However, for reusable components that need to pass "stuff" through to children, that strategy doesn't really work, so taking a standard `context.Context` in your template would likely be better.

I appreciate that some people find that tedious and want to use an equivalent of React's context provider so that they can avoid "prop drilling". I've touched on where we're headed here: https://github.com/a-h/templ/issues/109#issuecomment-1772316439

After the change in this issue, the current design direction is that if you want context, you have to accept it as a function param in your templates (all the way down), e.g.:

```
templ Child(ctx context.Context) {
  <button value={ ctx.Value("key") } />
}

templ Home(ctx context.Context) {
  // TODO: Use the ctx directly

  // You have to pass the ctx to any children.
  @child(ctx){}
}
```

And wire up the HTTP handler to use it to instantiate the template.

```go
func main() {
  h := http.HandleFunc(func(w http.ResponseWriter, r *http.Request) {
  // Pick up the request context, add a variable to it, and pass it to the template, while
  // also passing the updated context to any the `ServeHTTP` function.
  name := "test name"
  ctx := context.WithValue(r.Context(), "key", name) 
  templ.Handler(Home(ctx)).ServeHTTP(w, r.WithContext(ctx))
})
  http.ListenAndServe(":8080", h)
}
```

So you would then add `ctx` as a param to all your functions, update the handler setup and you'd be back up and running.

Of course, if the community thinks that this is a terrible idea, and it was fine how it was, we could roll back renaming just the `ctx` param (leave `w` and `err` as hidden) and document that `ctx` is an implicit variable that is always in scope within a template body and that changes to it affect child components.

I think that losing the implicit `ctx` variable somewhat harms composability, so I'm supportive of rolling back the `ctx` change if there's consensus.

The reason is that after this change, instead of doing something like this:

```go
func ConditionalRenderer(child templ.Component) templ.Component {
  return templ.ComponentFunc(func (ctx context.Context, w io.Writer) {
     if ctx.Value("group") == "admin" {
        ctx = context.WithValue(ctx, "isAdmin", true)
        // Child components can't access the ctx variable, so they can't use the "isAdmin" `ctx` value.
        child.Render(ctx, w)
     }
  })
}
```

You have to take a function that constructs the child if you want a generic one. However, you might not know all the other args for the constructor.

```go
func ConditionalRenderer(child func(ctx context.Context) templ.Component) templ.Component {
  return templ.ComponentFunc(func (ctx context.Context, w io.Writer) {
     if ctx.Value("group") == "admin" {
        ctx = context.WithValue(ctx, "isAdmin", true)
        // Have to call a function to construct the child, before rendering.
        child(ctx).Render(ctx, w)
     }
  })
}
```

On the side of keeping hiding the `ctx` and `w` variables, since there's no concept of a constant interface in Go, and you can't prevent variable shadowing, having `ctx` and `w` variables in scope does introduce a constant risk of breakage (change `w` to point to a nil writer etc.), so there's some value in the explicit nature of passing `ctx` as a function param to the template constructor.

Would love to hear everyone's thoughts on it!

**Comment by gungun974** [comment]
> It would also break people's code if they were using the context (`ctx`) variable, or the `w` variable.
> 
> For example, it could be that people decided to do something like this:
> 
> ```go
> templ Example(s string) {
>   if result, ok := db.GetResult(ctx, "1"); ok {
>      { result.Name }
>   }
> }
> ```
> 
> Or...
> 
> ```go
> templ Example(s string) {
>   if ok := sideEffectingFunctionThatWritesTo(w); !ok {
>      <div>There was a problem</div>
>   }
> }
> ```
> 
> That's why I'm still not 100% sure about the changes to the `ctx` and `w` variables. I think the change to the `err` variable, and the other internal `templ*` variables is safe.
> 
> The questions I want to answer before merge are:
> 
>     * Are we (as templ users), supposed to know that the `ctx` and `w` variables exist, and... should we use them?
> 
>     * If `ctx` doesn't exist, where should we get a context from?

Well personally it's just only now I upgrade my templ version and discovers this breaking change.

In my code I was using context to pass the current URL of the router for my Navbar.

This is very annoying because I need to change something that was working but it's seem looking through the templ generator code and what I can see is generate in project the "ctx" variable has just change name with `templ_7745c5c3_Ctx`.

I don't care if this name is ugly with this prefix. My only question now is this prefix `templ_7745c5c3_` gonna change since it didn't seam random and just hard coded ?

Excuse me if I'm appear a little angry, it's just I need to fix it for my work :sweat_smile:

**Comment by a-h** [comment]
@jonerer - just in case you don't spot it, see #253 for an update to this.
