### ISSUE TITLE
Errors got lost on-save

### ISSUE THREAD

**Issue by metaleap** [a-h/templ#202]
**Note: I'll be happy to attempt a fix PR (at _some_ point =) if** you let me know whether it's more likely in the `templ-vscode` extension repo or the `lsp` part of the `templ` prog.

- templ v0.2.364, none of its config-settings customized yet.
- `go version` go1.21.1 linux/amd64
- VSCodium 1.82.2 (settings `editor.formatOnSave` and `editor.formatOnType` both `true`)
- Linux (Void Linux, kernel 4.19.294_1, utterly irrelevant I'm sure)

Here's a repro file to play with (perhaps in an ideally fresh / blank workspace), initially correct:

```templ
package client

templ BarBaz() {
	<foo>if true { Bar<b>Baz</b> } </foo>
}
```

Now remove the very last `}` and diagnostics correctly shows an error. But save it and it's gone!

Now close and reopen the incorrect file. The error initially shows up correctly. But correct it and it stays! Save it and it still stays!

Now Cut the whole (just-corrected) `templ` and the error goes. But Paste it back in, it returns! Even renaming the `templ` won't help. But removing it's one line or just the `if` keyword will.

So it's a lil shaky yet as far as diagnostics-publishing goes  =)  mad props on this cool project either way tho!

**Comment by metaleap** [comment]
Whoa I even did a VSC reload (`workbench.action.reloadWindow`) and the mistaken `if: unterminated (missing closing '{
')` diagnostic just keeps on staying! Did another after repeated `killall templ` and it's still there. Are these persisted for some reason?!

The state of the file is the same as quoted originally in the beginning above.

**Comment by wdscxsj** [comment]
The same issue also occurred during my tests for #192.

**Comment by a-h** [comment]
Thanks for looking into this and for highlighting the issue.

I merged an update from @joerdav today that clarifies how the `for`,`if` and `switch` stuff should be used. It now checks for `{\n` as expected after an `if` block - https://github.com/a-h/templ/pull/216 - so, I *think* this issue might be fixed in the latest commit. I couldn't replicate the issue as you describe it with the latest.

However, reading this, I'm thinking that maybe the parser should allow elements etc. after the opening brace, but that the formatter should put it on a new line.

For example, in the Go playground, if you write this...

```go
package main

import "fmt"

func main() {
	if true { fmt.Println("test") }
}
```

It gets updated to:

```go
package main

import "fmt"

func main() {
	if true {
		fmt.Println("test")
	}
}
```

If you're interested in seeing how the LSP is actually seeing the files, there's some info on the debugging tools in the LSP at https://github.com/a-h/templ/issues/85 - You can inspect the internal model that the LSP has, including the templ source code to Go source code mapping.

The logs are reasonably good too.

**Comment by a-h** [comment]
Hi folks, I've just released https://github.com/a-h/templ/releases/tag/v0.2.408 - it contains a number of changes that are likely to impact or fix this issue.

In particular...

* fix: use full sync to reduce jank LSP behaviour
* feat: add useful error message for incomplete go statements
* fix(fmt): do not introduce additional whitespace where it affects rendering

If you're able to test again, that would be much appreciated.

**Comment by a-h** [comment]
I haven't had any reports of further issues since v0.2.408, so I think it's time to close this issue. Please re-open or create a new issue if there's still a problem here.

Thanks everyone!
