### ISSUE TITLE
How to reference nested templates?

### ISSUE THREAD

**Issue by PylotLight** [a-h/templ#226]
For a simple project of:
main.go
templates/hello.go
templates/hello.templ

I'm getting undefined on the generated function because it can only seem to see it if they are in the same root path. Typically with gotemplates I would nested templates to keep things separate especially when using embed. 

I haven't been able to import the function when the package is main or templates etc, is it possible to use nested folders? I can see something similar in the examples, so not sure what I'm missing.

**Comment by joerdav** [comment]
You should definitely be able to access nested templates, since the generated code is just Go code you can access it as you would any other function.

If you were able to provide a minimal reproduction repo on github that would be fantastic, then I would have more information to work on.

Also, thanks for trying out templ!

**Comment by PylotLight** [comment]
I spent some time with a helpful user on the go discord and was able to fix my issue by importing my local components package:
<package>"<modulename>/<subdir>"
