### ISSUE TITLE
Question regarding project name and logo

### ISSUE THREAD

**Issue by mhanberg** [a-h/templ#246]
Hi! Apologies, this isn't really an issue, but a question regarding the name and logo of the project.

I am the author of an Elixir HTML DSL, [Temple](https://github.com/mhanberg/temple), and I recently came across your project.

My question is, did you previously see my project and mimic the name and logo? They are eerily similar.

Regardless of the answer (I am just morbidly curious! 🤣), it is perfectly fine, I just found it so shocking to see another HTML related project called temple using the Permanent marker font as it's logo with `<` and `/>`

I will close this immediately after opening as it's not an actual issue, take care and good luck!

I have pasted a comparison of the logos below.

| My project  | This project |
| ------------- | ------------- |
| ![image](https://github.com/a-h/templ/assets/5523984/7cd750e9-e2a3-408b-99d0-eddf8e6bb8c7)  | ![image](https://github.com/a-h/templ/assets/5523984/06dc41e1-4920-43ca-a5a9-a04bdaa6f7da)
  |

**Comment by a-h** [comment]
Wow, no, I never saw your project! Just hearing about it today. 😁 

I can tell you about the name...

I wanted a name that was as close to "template" as possible, but far enough away from Go's built in "html/template" package to not confuse people.

In Go, you end up using the name of the repo fairly regularly within your code, since it's how things are namespaced (it's the package name), so I wanted a name that is small, and would also match the file extension.

However, Go developers tend to use a lot of short variable names (`t` for test inputs, `w` for an `io.Writer`, `r` for a HTTP request etc.), so I didn't want to go under 4 letters.

`templ` is shorter than `template`, and shorter when it's in your code. It couldn't be `templat`, because the `e` in template is already sort-of silent in my Northern English accent (i.e. `templut`).

It couldn't be `templa`, because then you're into "Knights Templar" territory. So... I ended up at `templ`, which... sounds like "temple".

I would have gone for `tmpl`, but I kept the `e` in the name because the `tmpl` file extension is already commonly used for the built-in Go templates, so I didn't want to clash with that, and also again, with my accent I'd be saying `tumple`. 😁 

So... it sounded like `templ`, so I originally came up with a logo that's ... sort of a temple, but was told very quickly that it looked terrible, and was maybe even offensive. I'm very much *not* a graphic designer.

I took a PR from my son, who updated the logo.

https://github.com/a-h/templ/commit/73b850b2d185c00aa8ac25c77048dc10668b3cf5

I think we made it together on his Linux machine, instead of my Mac. IIRC, we just opened up Gimp and, I said I wanted something that looked like HTML, so I thought `</>` would work because it's sort of what you get when you Google HTML logo:

![image](https://github.com/a-h/templ/assets/1029947/a8e8d1a0-be36-4541-a97b-b93a9811e788)

And then I just went through all the fonts until I thought it looked like enough like a logo, and got back on with some coding! 😂 

The colours were picked so they'd work on dark and light backgrounds.

Up until today, people have only mentioned the name clash with the obscure operating system https://en.wikipedia.org/wiki/TempleOS

Did we basically have the same thought process?

**Comment by a-h** [comment]
So, yes, complete accident. Sorry about that!

It seems I should get an issue on here for a new logo...

**Comment by mhanberg** [comment]
Yes, almost exactly the same haha. I opened figma, found a font I liked, typed it out and threw some angle brackets on there. 

And no need to update your logo if it works for you! The packages live in different ecosystems so confusion is unlikely. 

And your project seems to get more usage than mine, anyway!

I also have gotten the TempleOS thing haha

**Comment by mhanberg** [comment]
> So... it sounded like templ, so I originally came up with a logo that's ... sort of a temple, but was told very quickly that it looked terrible, and was maybe even offensive. I'm very much not a graphic designer.

I actually did the exact same thing and came to the same conclusion haha
