### ISSUE TITLE
Document highlight on vscode behaves strangely

### ISSUE THREAD

**Issue by ross96D** [a-h/templ#283]
When i put the cursor starts highlighting random places. Like on the images below

![templ_Highlighting_issues_3](https://github.com/a-h/templ/assets/79549577/e83e74ab-c356-4548-b2ad-ea8655230063)
<br>
![templ_Highlighting_issues_2](https://github.com/a-h/templ/assets/79549577/95d34707-c7ac-4f08-b2b3-c9c3d2b7a66d)
<br>
I did this on an html file and almost never highlight. The one that i found was when i put the cursor on a div and it highlights the div and the closing div. Like below
![image](https://github.com/a-h/templ/assets/79549577/fbdbfd6a-2171-4334-8a5f-343768c249a2)

**Comment by a-h** [comment]
Hi @ross96D - thanks for raising this. The issue was that templ proxies LSP requests through to gopls in order to get results from the generated Go code. I did a talk about how it works at Gophercon UK this year.

In this case, there's no sensible mapping between things you're highlighting in VS Code, and the underlying Go code.

<img width="1512" alt="Screenshot 2023-11-12 at 15 59 11" src="https://github.com/a-h/templ/assets/1029947/0e3eaafa-ccff-4971-8f13-bccd2f5f1081">

There's a web server option in the templ LSP that shows you the underlying mapping. In this case, by adding to the logs, and looking at the view, I could see that when I was highlighting something in VS Code, it was sending it through to the templ LSP, and that was highlighting the positions of various bits of underlying Go code, so it looks totally random!

<img width="1512" alt="Screenshot 2023-11-12 at 16 04 15" src="https://github.com/a-h/templ/assets/1029947/1b50b795-9e52-498a-a511-df828c69c238">

I think the most sensible thing to do here is to not return any highlights from templ. Later on, if we want, we could implement some templ specific highlighting, but since tokens aren't often repeated, it's probably not very useful in templ.

No change is needed in the VS Code plugin, it's just a change to the templ CLI which runs the LSP.

Thanks again!
