### ISSUE TITLE
Possibility use unsafe string

### ISSUE THREAD

**Issue by ssimk0** [a-h/templ#289]
Similar to html/template, it would be amazing to be able to render unsafe string ( html template from database for example)

```
template.HTML("<p>Paragraph</p>")
```

it will be great to be able do it somehow like : 

```
		<div class="container page">
			<div class="row">
				<div class="col">
					{ templ.UnsafeString(content) }
				</div>
			</div>
		</div>
```

or there is some way how to do it ?

**Comment by a-h** [comment]
There is a way to do it, it's discussed in https://github.com/a-h/templ/issues/175#issuecomment-1742205959

The question we haven't decided on is whether to include the capability to do it, as per React's `dangerouslySetInnerHTML`.

In templ, at the moment, all Go strings are classed as "unsafe" and therefore need escaping before output, because it's not possible to identify which Go strings are under the programmer's control.

**Comment by ssimk0** [comment]
@a-h thanks for pointing me at least :) Hopefully you will include it also to templ with better ergonomics :)
