### ISSUE TITLE
Question: generate in a different directory

### ISSUE THREAD

**Issue by fkarakas** [a-h/templ#291]
Hello,
Is it possible to generate the go files in another directory than the .templ, because it can become hard to navigate with many templates, the idea is to generate in other folder with the same "sub directory structure" without "poluting" the original directory containing all the .templ files.
Regards

**Comment by a-h** [comment]
It's not currently possible. the templ LSP needs to be able to calculate where the Go file would be.

From a Go point of view, the directory name is usually the same as the package name, so if the output Go files were in a different directory, wouldn't the package name be different?

Most editors allow you to set up rules to hide files you don't want to see. For example https://stackoverflow.com/questions/30140112/how-do-i-hide-certain-files-from-the-sidebar-in-visual-studio-code

Does hiding the files solve the problem?

**Comment by fkarakas** [comment]
I see what you mean and it can be a solution (i will try the vscode solution) but i think it is not optimal.
Perhaps one way to do it would be to put all generated code in a single file per package ? i don't know...

```md
├── pages
│   ├── templ_generated.go
│   ├── index.templ
│   ├── page1.templ
│   ├── page2.templ
│   ├── page3.templ
├── components
│   ├── templ_generated.go
│   ├── component1.templ
│   └── component2.templ
```

**Comment by joerdav** [comment]
It's definitely possible, that could be a templ generate flag as I don't think this should be default behaviour. 

I'm curious as to why hiding the generated files is not optimal? This is sort of the approach that github takes, it doesn't show generated files by default: https://github.com/a-h/templ/commit/43545f88a52c9259c2a498a0914cbc2307d37c8f

**Comment by OrlandoCo** [comment]
Single file per package looks like a good solution for me, maybe behind a flag ?

**Comment by a-h** [comment]
I'm not particularly keen on having a flag to change the behaviour. It makes maintenance of templ harder, since you have to handle both cases, and not accidentally break the non-default one. If one person generates with the flag, and another without, then you get duplicated code, and compiler errors.

I'm not keen on combining everything into a single file, because to generate code for a single templ file, you'd have to do the whole package sequentially instead of being able to generate files in parallel.

What editors are you using where this is a problem?

For example, we could update the VS Code plugin to hide the `_templ.go` files easily enough using https://code.visualstudio.com/api/references/contribution-points#contributes.configuration to set `"files.exclude": {  "*_templ.go": true }`.

**Comment by fkarakas** [comment]
"The biggest communication problem is we do not listen to understand. We listen to reply.”
― Stephen R. Covey

This is my feeling here, anyway, thanks for your replies.

**Comment by a-h** [comment]
I am trying to listen, I simply don't understand what the issue is. I just can't imagine what problem having the generated files next to the templ code is causing you. I don't hide the files in my editor or in my terminal output, and I don't have an issue with it.

You said it's hard to navigate the files, but I don't know what you're using to navigate the files. I guessed you were using an editor of some sort to navigate, so suggested that it could be configured differently to hide them - and maybe that would solve the problem.

You said it wasn't optimal to hide the files, but didn't explain what your idea of optimal is, and why.

Changing the software to support having two ways of working gives me the potential of future downstream problems with the change, so before I spend my time coding a change, I want to understand what problem I'm solving, that's all.

I only have so many hours, so I need to prioritise...
