### ISSUE TITLE
How do we pass `this` element in the onclick handler?

### ISSUE THREAD

**Issue by cayter** [a-h/templ#296]
How would the below look like in templ? I can't seem to find `this` usage from the doc [here](https://templ.guide/syntax-and-usage/script-templates).

```
<h3 onclick="myFunction(this, 'red')">Click me to change my color.</h3>

<script>
function myFunction(element, color) {
  element.style.color = color;
}
</script>
```

**Comment by a-h** [comment]
Hi @cayter,

Sorry for the long wait for a response on this.

What you've written works fine without change in templ.

```templ
package main

templ page(global, session int) {
	<html>
		<head>
			<meta charset="UTF-8"/>
			<title>OnClick</title>
		</head>
		<body>
			<h3 onclick="myFunction(this, 'red')">Click me to change my color.</h3>
			<script>
				function myFunction(element, color) {
					element.style.color = color;
				}
			</script>
		</body>
	</html>
}
```

![onclick](https://github.com/a-h/templ/assets/1029947/2f1904e3-539b-45e2-899d-941545e8c82c)

But I think that what you mean is, how could you use a script template so that you can use Go variables within the script?

Here's how you might create a reusable `changeableHeader` component which generates a namespaced script for `changeColor` to prevent it clashing with other scripts, and only renders the script contents once per context.

```templ
package main

script changeColor(id, color string) {
	document.getElementById(id).style.color = color;
}

templ changeableHeader(id, color string) {
	<h3 id={ id } onClick={ changeColor(id, color) }>
		{ children... }
	</h3>
}

templ page(global, session int) {
	<html>
		<head>
			<meta charset="UTF-8"/>
			<title>OnClick</title>
		</head>
		<body>
			@changeableHeader("elementId", "red") {
				<p>Header text</p>
			}
		</body>
	</html>
}
```

The HTML output is:

```html
<html>
   <head>
      <meta charset="UTF-8">
      <title>OnClick</title>
   </head>
   <body>
      <script type="text/javascript">function __templ_changeColor_c14b(id, color){document.getElementById(id).style.color = color;}</script>
      <h3 id="elementId" onClick="__templ_changeColor_c14b(&#34;elementId&#34;,&#34;red&#34;)">
         <p>Header text</p>
      </h3>
   </body>
</html>
```

I'd love suggestions or a PR on how to make it clearer in the docs. Maybe it's a case of adding the examples above?

**Comment by cayter** [comment]
Ah yes, that's what I meant. Good to know there's a workaround using just document selector, thanks!

**Comment by esnunes** [comment]
What if I want to return the value of the script call, e.g.?
```html
<form onsubmit={ fnReturnBool()}>
```

to prevent the form from being submitted I need the generated function all to have the `return` statement e.g.:

```html
<form onsubmit="return hash_fnReturnBool()">
```
