### ISSUE TITLE
Docs and latest release seem to be out of sync

### ISSUE THREAD

**Issue by dngferreira** [a-h/templ#298]
Hey,
I would like to start by congratulate on a wonderful project and a great help simplifying  web development in Go.

I was going through the documentation and it seems that some features that are referred to on the docs are not available on the latest release, as an example the Javascript functions Rendering with `@` syntax.

Thanks.

**Comment by a-h** [comment]
Yes, you're right. I need to push a new release of templ to pull together all the new features.

There has been 41 commits since the last release of templ https://github.com/a-h/templ/compare/v0.2.432...main

Script components were committed 2 days ago in https://github.com/a-h/templ/commit/abe23c6859682ffa0bb53bb2c78d058e28c197bc

I'll probably be able to push a release tomorrow.

**Comment by a-h** [comment]
I probably need to change the release strategy for docs, at the moment, it deploys on every push. Probably needs to deploy on a push of a new tag.

**Comment by a-h** [comment]
Thanks, it doesn't solve the problem for this set of changes, but will make sure that features that haven't been released yet don't appear in the docs.

And thanks for your comments about the project!
