### ISSUE TITLE
Compile Error boolConstantAttributeParser when end with `/r`

### ISSUE THREAD

**Issue by rizal111** [a-h/templ#300]
I got a compile error when the bool attribute ended with the new line. It work when I move the close tag beside it and my formatter just it shift back to newline 🤣 . or I just apply the value `required="true"`.

My code : 

```
<input
   ...restAttribute
   required
/>
```

The error: 

`parsing error: boolConstantAttributeParser: expected attribute name to end with space, newline, '/>' or '>', but got "\r"`

**Comment by a-h** [comment]
I think it's getting confused by `...restAttribute`, since adding this test to `elementparser_test.go` works fine.

```go
		{
			name: "element: bool constant attributes can end with a newline",
			input: `<input
   required
/>`,
			expected: Element{
				Name:        "input",
				IndentAttrs: true,
				Attributes: []Attribute{
					BoolConstantAttribute{
						Name: "required",
					},
				},
			},
		},
```

Spread attributes aren't in templ (at least, not yet) as per https://github.com/a-h/templ/pull/237 and https://templ.guide/syntax-and-usage/attributes

From what I can see, the current PR for rest attributes only deals with passing string attributes down via the rest attribute, which I don't think is sufficient, but I haven't had chance to really think it all through.

I'm interested in how you want to use the `...restAttribute` to feed into the design.

**Comment by rizal111** [comment]
My bad ```...restAttribute``` not my in code just the rest of my attributes that I do not show. This is how the error looks like in my vscode I can't end with ```/r```. I have no idea what's wrong.

![image](https://github.com/a-h/templ/assets/61342066/1aa0b847-5f79-41e3-ac26-d9c861712337)

**Comment by a-h** [comment]
Thanks, I see the issue now. The parser wasn't looking for Windows line breaks. I've updated the parser, added a new test in the commit above, and the fix will be included in the next release.
