### ISSUE TITLE
[feature idea] Support Non-String Variables in Templates

### ISSUE THREAD

**Issue by hienvl125** [a-h/templ#307]
## Problem
Currently, it only supports string variables inside curly braces `{}`. This limitation forces users to convert non-string variables to strings explicitly, which can be leads to less readable code.

## Feature Proposal
I propose enhancing the `templ` package to support non-string variables directly inside curly braces `{}`. This improvement will allow users to write cleaner and more readable code when working with HTML templates.

### Current Implementation
```go
templ TodoComponent(name string, point int, completed bool) {
    <div>
        <p>Todo's name: { name }</p>
        <p>Todo's point: { fmt.Sprintf("%d", point) }</p>
        <p>Todo's status: { fmt.Sprintf("%t", completed) }</p>
    </div>
}
```
### Proposed Implementation
```go
templ TodoComponent(name string, point int, completed bool) {
    <div>
        <p>Todo's name: { name }</p>
        <p>Todo's point: { point }</p>
        <p>Todo's status: { completed }</p>
    </div>
}
```

**Comment by a-h** [comment]
Thanks for that!

I'll give you a bit of the background on why it is, and see if it sparks some ideas on if/how to proceed. 😁 

I originally chose to keep it simple and force the use of strings to make it explicit about how values would be rendered to a string.

I thought that usually, I want control of how everything is rendered on a web page. For example:

* Just because something is an integer, doesn't mean that I want to display it without thousand separators, and those are different in different languages (e.g. German uses `1.000` while English uses `1,000`).
* I typically want to choose a number of decimal places for floats.
* Date formats usually need some consideration for localisation.
* I don't know *what* I want to display for most structs.
* I definitely don't want to try and display a pointer address.

Here's a few examples of what would happen if templ chose to render everything with `%v`: https://go.dev/play/p/LCscSrbQROA

Also, if templ allows the `any` type to be rendered, there's a bunch of rendering errors that would be moved from being a compile time error to being a runtime bug. For example here, it's obvious that I should have called `Field()` as a method, not passed `Field` as a value, but I get `0x47aaa0` rendered at runtime instead of the value.

https://go.dev/play/p/3x1vrZrcPlO

In the https://github.com/a-h/templ/blob/main/CONTRIBUTING.md doc, I refer to the idea of preferring compile time over runtime errors, i.e. if there's a choice of developers (me!) needing to be more explicit to offset a risk of something affecting users, I prefer the developer hassle.

So... what could be done?

* Use the default render, and let developers sort it out.
* Add a map of type to `String()` functions that can be used to customise how templ renders stuff (probably has runtime cost).
* Add a new templ expression type that does string formatting, e.g. `{v 123 }` would use `%v` to render it.
* Something else I haven't thought of.

Any thoughts?

**Comment by joerdav** [comment]
Some options come to mind:

Accept either type `string` or `fmt.Stringer`

Or without depending on another package:

Accept `templ.TemplateStringer` or any primitive type?

`~int | ~string | ... | templ.TemplateStringer`

```go
type TemplateStringer interface {
    TemplateString() string
}
```

Then it's a little more concise in templates:

```go
type Grams int

func (g Grams) TemplateString() string {
    return fmt.Sprintf("%dg")
}

templ Index() {
    <p>{Grams(100)}</p>
}
```

Excuse any typos I jotted this down on mobile so it didn't leave my brain!

**Comment by a-h** [comment]
This is one of the spots that I'm constantly brushing up against with Go's generics.

<img width="664" alt="Screenshot 2023-11-26 at 21 06 53" src="https://github.com/a-h/templ/assets/1029947/6346558a-99eb-421c-be16-7f479f10f6f7">

I want to use generics to deliberately constrain the types that can be passed to a function or method and to have a compile-time check, not a runtime check, but Go seems to get in the way here. No discriminated unions, and since there's no function overloads in Go either, no way to do it that way either.

https://github.com/golang/go/issues/49054

IIRC, I've seen people in the Go community say "use any" and do a runtime type check, which would be fairly rubbish here.

**Comment by lukpank** [comment]
My workaround is to define in the package with HTML templates
```go
var S = fmt.Sprint
var F = fmt.Sprintf
```
then I can write for example
```jsx
<p>{ S(something) }, { F("%g", someFloat) }</p>
```
