### ISSUE TITLE
Unable to try out Pull Request

### ISSUE THREAD

**Issue by cmar0027** [a-h/templ#310]
I wanted to try out the new changes in #237 on a project I'm working on, as this PR would make a lot of things easier for me, but there's a problem that prevents me from doing this. 

Unless I'm missing something, I think this problem may also prevent anyone from trying out other PRs, so this issue might be useful for others as well.

The kindest thanks to whoever can help me out.

## What I did
I cloned https://github.com/gungun974/templ (the PR's repo) and installed it with
```bash
rm cmd/templ/lspcmd/*.txt || true
go run ./get-version > .version
cd cmd/templ && go build -o ~/bin/templ
```

## Problem
File generation from `.templ` files is successful, however, the generated files import `"github.com/a-h/templ"`, which obviously doesn't have the definition for `templ.Attributes` yet, causing an error:

Sample generated file import section:
```go
// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.468
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"
```

Screenshot of error in generated file:
<img width="584" alt="image" src="https://github.com/a-h/templ/assets/52538393/4f673349-de14-4e66-a9fd-ccfd15643ba0">

**Comment by gungun974** [comment]
Oh you make me discover the import of the Templ Runtime is hard coded. In fact the line responsible to create the line `import "github.com/a-h/templ"` https://github.com/a-h/templ/blob/499671ce79d0807c8016d608566fc48ad4ae6c46/generator/generator.go#L141

I'm not the owner of this repos so this is my personal opinion but I think this should remain hard coded with the main repo. The only reason to change is if someone fork this project to create a parallel variation of Templ.

You should not use Github fork meant to be only a PR. 

For example my repo (https://github.com/gungun974/templ) is not up to date with the upstream since it's a temporary Github Repo for my personal contribution to this project.

So if for example you try to use in my repo the branch `spread-attributes`. You will get an outdated version of Templ since the thing I need to merge in my PR #237 don't have conflict with latest.

So I can't really recommend anyone to just "import" a branch of a PR. (Unless you fork and rebase it to `main` and inspect it before using it)

But If you really insist to try out in your project a PR. You need to add to your build step (for example `MAKEFILE`).
A search and replace for every file with `_templ.go` at the end with the correct runtime Import. (You also need to don't forget install in your go module the "fork" runtime)

Also beware in my repo of #237. It's not the branch `main` but `spread-attributes` that got the proposal implementation. And again it's not up to date and a "proposal" so not production Ready ! (And I don't mention that technically you download an none official version of Templ).

Anyway, that was all I wanted to say about this issue. I hope that in some way I helped you despite having been very bitter :sweat_smile:

**Comment by cmar0027** [comment]
Thanks a lot @gungun974 for your reply. 

Yes, I do understand the consequences of using a branch of a PR, but since I'm optimistic that the spread syntax, or something similar, would eventually make it to templ, and since I really need it, my goal was to use your version until the spread attributes syntax (or something analogous) gets merged, then switch back to the official templ.

I'll try to make a simple build step, as you suggested, and publish it here for anyone interested. 

> It's not the branch main but spread-attributes that got the proposal implementation
Thanks, I didn't realise that!

> You also need to don't forget install in your go module the "fork" runtime

Before opening this issue I tried manually changing the runtime import path to use yours (as the build step would do) but I couldn't find a way to install it because I don't know how to use `go get` to install a local module. Do you happen to know how to do this?

**Comment by a-h** [comment]
I think a Go module "replace directive" might work. You can point a go module path to another location by adding one to the go.mod file.

**Comment by cmar0027** [comment]
I can confirm that a replace directive as suggested by @a-h  works like a charm, no need for a custom build step.

This is my go.mod file:
```
module github.com/cmar0027/myproject

go 1.19

replace github.com/a-h/templ => /Users/cmar0027/dev/templ

...
```

**Comment by a-h** [comment]
Great, glad to hear you got it sorted. I'm still thinking about the spread attributes, I think we need to support multiple attribute types, not just string attributes.

**Comment by gungun974** [comment]
> Great, glad to hear you got it sorted. I'm still thinking about the spread attributes, I think we need to support multiple attribute types, not just string attributes.

Interesting, what do you mean with "multiple attribute" ? In pure HTML tag can only received key/value string ?
Have you an example when a simple string don't conform with that ?

**Comment by a-h** [comment]
I've carried on the conversation here https://github.com/a-h/templ/pull/237#issuecomment-1849872445 where it will be easier to find in the future.
