### ISSUE TITLE
undefined context

### ISSUE THREAD

**Issue by mybigman** [a-h/templ#312]
RE: https://github.com/a-h/templ/issues/275#issue-1973235589

This still appears to be an issue. The code runs however constantly complains :/

```fish
> templ version
0.2.476
```

```go
// mod.go
github.com/a-h/templ v0.2.476
```

<img width="407" alt="2023-12-06 at 23 51 43@2x" src="https://github.com/a-h/templ/assets/1289916/5e90fe7e-5e61-4285-a318-85bec44a394f">

**Comment by a-h** [comment]
Since the change was a change to the generator behaviour, you'd have to use templ v0.2.476 to re-generate the `{name}_templ.go` files to see the changes applied.

The unit tests at https://github.com/a-h/templ/tree/main/generator/test-context cover the expected behaviour of the context variable, and they're currently passing.

From the brief snippet you've included above, I don't see how what you've done is a problem, so I'm fairly confident it's an issue with needing to re-generate Go code with a later version of templ.

A repo with a minimal reproduction would be handy, since otherwise it's not very clear what the issue is.

**Comment by davidjdriver** [comment]
I was following Anthony GG's video today and ran into the same thing. I upgraded to the latest version of the templ command and I can now run the build but vs code's templ plugin still reports the syntax error.

**Comment by mybigman** [comment]
@davidjdriver the only way i found to stop it from squawking was to add the below to the head

```go
var ctx context.Context
```

**Comment by a-h** [comment]
Hi folks, I'm going to need to see a reproduction repo to be able to help with this...

**Comment by a-h** [comment]
No reproduction provided, having to close because I can't reproduce the issue to debug it.

On the good news, a new version is out today, which includes lots of improvements and fixes.
