### ISSUE TITLE
Rendering multiple charts

### ISSUE THREAD

**Issue by ziganagelj** [a-h/templ#313]
I dont really see many examples on how rendering charts would work. The only this i see is: https://templ.guide/syntax-and-usage/script-templates.

I however want to build multiple individual components and the combine them into a grid, but i had no success rendering the chart with anything else apart from onload in body, which doesn't work when combining multiple charts.

Individual chart:

```
templ CategoryMonthAmountBarChart(aggregate []domain.TransactionAggCategoryMonth) {
    <body onload={ graphBar(aggregate) }>
        <canvas id="categoryMonthAmountBarChart"></canvas>
    </body>
}
```

Grid:
```
templ ChartPage(aggregate []domain.TransactionAggCategoryMonth, term string) {
	@shared.Page("Data") {
        <div class="container mx-auto px-4 py-6">
            <h1 class="text-3xl font-bold mb-6">Spending Insights</h1>

            <div class="grid grid-cols-1 gap-6">
                <div class="bg-gray-800 p-6 rounded-lg shadow-lg">
                    <h2 class="text-2xl font-bold mb-4">Total Monthly Spending by Category</h2>
                    @partials.CategoryMonthAmountBarChart(aggregate)
                </div>
            </div>
            <div class="grid grid-cols-1 gap-6">
                <div class="bg-gray-800 p-6 rounded-lg shadow-lg">
                    <h2 class="text-2xl font-bold mb-4">Total Monthly Spending by Category</h2>
                    @partials.CategoryMonthAmountBarChart(aggregate)
                </div>
            </div>
        </div>
    }
}
```

**Comment by a-h** [comment]
I'd love to help out. Do you have, or can you make a minimal example of what you're trying to do and share it in a Github repo? That way, I can see exactly the libraries you're using, and how it is all fitting together.

**Comment by ziganagelj** [comment]
Hey, i managed to put everything on github now (its my frist go and web project) - https://github.com/ziganagelj/spendings
https://github.com/ziganagelj/spendings/blob/main/internal/templates/pages/charts.templ is where i combine the two charts.
Thank you for the help!

**Comment by a-h** [comment]
I was hoping for a more minimal example rather than your entire project, but your project looks very well structured, so it was fairly easy to follow. Reading through, it looks like you are rendering two extra `body` elements and setting two `onLoad` attributes on those body attributes, when in HTML, only one body element is permitted.

Here's the two locations:

https://github.com/ziganagelj/spendings/blob/1a21c84c6d2f0e4d70d747b0029b4f4d4a4f3ce8/internal/templates/partials/categoryMonthAmountCumulativeBarChart.templ#L75-L79

https://github.com/ziganagelj/spendings/blob/1a21c84c6d2f0e4d70d747b0029b4f4d4a4f3ce8/internal/templates/partials/categoryMonthAmountBarChart.templ#L70-L74

Aside from that, it looks OK.

As per https://templ.guide/syntax-and-usage/script-templates - I think you'd need to rework your graphs to something like this (I haven't tested it) and keep the body tag for use just inside the `shared/page.templ` file.

```templ
templ CategoryMonthAmountBarChart(aggregate []domain.TransactionAggCategoryMonth) {
    <div>
        <canvas id="categoryMonthAmountBarChart"></canvas>
    </div>
    @graphBar(aggregate)
}
```

**Comment by a-h** [comment]
@ziganagelj - I assume my answer helped? If not, feel free to re-open.
