### ISSUE TITLE
Proposal: DEV Mode

### ISSUE THREAD

**Issue by stephenafamo** [a-h/templ#318]
Right now, development is sort of slow with `templ` because each change requires my entire application to be recompiled. For example, changing a class on a `div` requires 5 seconds before I can see it in my browser.

I would suggest having a "DEV mode" e.g. `templ generate --watch --dev-mode`

In this mode, instead of fully generating the static template code, some parts of the code are generated in the filesystem. This way, a full rebuild is not required each time something in the template changes.

I understand that this is difficult in reality since the templ code interfaces with the Go code, but I think there is a way to make this work.

1. The template is split into "static strings" and "go code".
2. Anytime part of the "go code" changes, then a full rebuild is required.
3. The static strings are put in a separate file where they are read from each time. This can be modified without needing the application to be rebuilt.

If it will be too complex to maintain both rendering modes, they could be combined such that in **dev mode**, the filesystem is read each time, but in **prod mode** the static strings are embedded with `//go:embed`

**Comment by a-h** [comment]
Great idea, and great ideas on the implementation too - it sounds quite practical.

I think that two generation modes would work best, since otherwise we'd have to have the concept of a "StringProvider" - something to look up the values of strings by their integer IDs so that we could swap implementation between dev and prod. Having a `StringProvider` would harm runtime performance, since we'd go from pushing a string constant, to making a virtual function call, but having two generation modes isn't too painful.

The change would be in this part: https://github.com/a-h/templ/blob/ddb1610a81627f5c9c524bb66877477f401e4ecd/generator/generator.go#L1280-L1294

We'd have to add a mode to the generator struct at https://github.com/a-h/templ/blob/ddb1610a81627f5c9c524bb66877477f401e4ecd/generator/generator.go#L55 and possibly add a `Strings []string` field to it. When we generate the file in dev mode, instead of loading the string directly, the generator would have to write out some code that requests a string by its id - for example, `templ_var_1, err := templdevmode.GetString("./{relative_path}/name.templ", templ_templateHash421, 1)`.

Since the generator adds strings to the `Strings` slice, in dev mode, the `templ generate` command can be updated to write them to disk (maybe as `{template_name}.templdev` so they can be added to `.gitignore`/`.ignore` files and/or deleted), and the `GetString` function can load them from disk on every render.

To avoid messing about with disks at all, the templ LSP could start a server, and the web app could connect to it when it's in dev mode. The templ LSP already compiles templates on basically every keypress, so it could compile the `Strings` slice. It also gets a notification when "save" is pressed in the editor, so it could push a reload event back to any apps that are connected.

To detect if extra Go code has been added which should force a complete reload, a hash of the template would need to be calculated and stored in each template. The hash could be as simple as printing the overall structure of the template file with all the HTML taken out, and running that through SHA256.

```
if { x == y} {
  for i := 0; i < 10; i ++ {
  }
}
```

Maybe it's crossing the streams a little, but if the hash changes and therefore, we need a regenerate, in dev mode, maybe the templ hot reload middleware could render a web page that lets you click "re-generate", where it runs the `templ generate` command for you, and restarts itself (it could grab `os.Args` and find out what the command line flags were/are).

I guess the main question would be whether this would really result in faster application dev. It wouldn't be great if the extra complexity didn't have a meaningful payoff in performance.

These are just ideas at the moment... I think that having a written-up design that we all agree on would be a good start as per https://github.com/a-h/templ/blob/main/CONTRIBUTING.md

**Comment by stephenafamo** [comment]
Writing out a more structured proposal now, and I think this `--dev-mode` should be combined with `--watch`

1. `--watch` is only used during development
2. `--dev-mode` is not very useful if the files are not being watched
3. Ideally, we want to "cleanup" after the dev mode ends. So, when the `--watch` command receives the end signal, it should cleanup the static string files and generate the templates for production. This way, a user does not even have to run another command to generate the production templates.

**Comment by stephenafamo** [comment]
About integrating with the LSP, I would prefer to avoid that because I think this should be able to work without the LSP.

**Comment by stephenafamo** [comment]
Improved proposal in #340 

Let me know if I should add more details
