### ISSUE TITLE
Comments inside `.templ` files above templ component get an extra line

### ISSUE THREAD

**Issue by edmondwinston** [a-h/templ#335]
I've search the docs and issues, apparently (maybe I've missed it) no one has reported it. Is this behaviour intentional due to some reasons?

Thank you!

![templ-comment-fmt](https://github.com/a-h/templ/assets/132081506/b28ae426-0bb6-4115-bc2f-4c92a5d872a9)

**Comment by a-h** [comment]
No, that's not intentional. I can reproduce it on the `main` branch, looks like a bug.

The formatting tests in `./parser/v2/types_test.go` don't cover the situation. There are tests for comments inside templ component definitions, but there isn't one for a Godoc style comments.

Investigating further, it looks like this https://github.com/a-h/templ/blob/d61470219c74a0bfc3a2a7f18f937fd943b68c30/parser/v2/types.go#L137-L141 is where the issue is.

Currently, between nodes (e.g. the Go code, and the templ statement), the formatter inserts two linebreaks. The intention here is to make sure that `templ` statements etc. have an empty line between them.

However, in this case, we only want one newline, because the Godoc comment should be above the templ statement.

The parser is currently identifying the first block of Go code up until the templ statement as the type called `TemplateFileGoExpression`. Since it's Go code, it makes sure there's a newline above the templ file by adding the two line breaks.

I think that the `TemplateFile.Write` method could check to see whether the current node is a `TemplateFileGoExpression`, and if it is, it ends with a comment, and the next node is a `HTMLTemplate` it only inserts a single line break between the nodes.

Alternatively, the `HTMLTemplate` parser could be updated so that it includes Go comments above it within its own object definition.

If you feel like having a crack at a fix, you can insert this test case into the table:

```go
		{
			name: "godoc comments are preserved",
			input: ` // first line removed to make indentation clear
package main

// test the comment handling.
templ test() {
	Test
}
`,
			expected: ` // first line removed to make indentation clear
package main

// test the comment handling.
templ test() {
	Test
}
`,
		},
```

Thanks!
