### ISSUE TITLE
Tailwind CSS integration

### ISSUE THREAD

**Issue by IoTcSolutions** [a-h/templ#352]
Hello, I see others have figured this out but I am having an issue integrating tailwind into my templ project. I have a tailwind config file in the root that looks like this:

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./views/*.{templ}"],
  theme: {
    extend: {},
  },
  plugins: [],
}

It works perfectly if I import the CDN directly into my main layout.templ file but I can't seem to get the production way of using the css to work. I can reach the output.css file generated by the command, but none of the styles show up. I get this warning:

warn - The glob pattern ./*.{templ} in your Tailwind CSS configuration is invalid.

Any help would be greatly appreciated.

**Comment by IoTcSolutions** [comment]
I was able to get the warning away by just using ./templ instead of ./*.{templ}. But the styles are still not applied.

**Comment by CalumMackenzie-Chambers** [comment]
@IoTcSolutions

The issue here is with the way you are trying to configure the content section. You can read about that [here](https://tailwindcss.com/docs/content-configuration)

If you are only checking in templ files you have no need for the curley brackets, they can be used to specify multiple filetypes, e.g your brackets could contain {templ,js} if you also were adding classes in any .js files.

As for the path I am assuming that views is a folder in your route directory so your structure would be the following

```
.
├── tailwind.config.js
└── views
    └── example.templ
```
In this case your glob pattern would be `"./views/*.templ"` (note you are missing the star from your config)

This * in this case denotes any file

However if you also have any subdirectories that you also want to watch within the views folder you could use the more general pattern `"./views/**/*.templ"`. This tells tailwind to also match any number of subdirectories inside the views folder.

In this example I have assumed that your views folder is at the root of your project, however if not you will have to include the full path to your views folder. `"./path/to/views/**/*.templ"`

Hope this helps

**Comment by IoTcSolutions** [comment]
@CalumMackenzie-Chambers You are the best! Hopefully this will help some other schlub like me! Have a great new year.

**Comment by IoTcSolutions** [comment]
Solve by @CalumMackenzie-Chambers
