### ISSUE TITLE
docs: explain how to integrate with vim

### ISSUE THREAD

**Issue by egtann** [a-h/templ#363]
There's lots of docs for integrating with neovim here: https://templ.guide/commands-and-tools/ide-support/

It would be great to document how we can add "Format on Save" support to vim itself.

**Comment by a-h** [comment]
I have no idea how to do this. It's probably a case of writing an autocmd to pipe through the `templ fmt` command instead of using the LSP API like Neovim can.

https://github.com/a-h/dotfiles/blob/33ea545ce1b0cca457c46b4689f745130eee5091/.config/nvim/lua/lsp.lua#L13-L14

I'd be happy to take a PR for the docs update if you find a way that works.

**Comment by iefserge** [comment]
This vimrm config worked for me:

```vim
set autoread
autocmd BufWritePost *.templ silent! execute "!PATH=\"$PATH:$(go env GOPATH)/bin\" templ fmt <afile> >/dev/null 2>&1" | redraw!
```

- `set autoread` to automatically reload file on save
- This sets `PATH` so doesn't require `templ` to be in PATH (only installed in go env bin)
- Pipe stdout/stderr to /dev/null, to avoid screen blinking on save

**Comment by egtann** [comment]
This works great! Thank you!

**Comment by a-h** [comment]
So, do we need another docs update to close this off, or are we happy we've got enough info now?

**Comment by egtann** [comment]
I think it’d be smart to include it in docs, since Vim is a widely used editor, and this is such an easy and dramatic way to improve the developer experience.
