### ISSUE TITLE
Wholesale dynamic attributes

### ISSUE THREAD

**Issue by thecsw** [a-h/templ#369]
Good evening! I have been working with `templ` and wanted to inquire whether this feature of having "wholesale" dynamic attributes is not supported by design or maybe I'm not being idiomatic—

Say, I have a visible variable, `customTags`, which would look like `style="width:100px";`, so it's a fully-formatted attribute with both the key and the value. Because it's already in the "final" form, according to the docs, https://templ.guide/syntax-and-usage/attributes, I should be able to (assume it's a part of a `templ` method in a `.templ` file(

```templ
<div class="media" { customTags }></div>
```

However, that would raise an error of

```
parsing error: if: expected nodes, but none were found: line 48, col 27
```

Similarly, if I try,

```
<div class="media" @templ.Raw(customTags)> </div>
```

or

```
<div class="media"
if true {
    { customTags }
}>
</div>
```

all results in the same error.

Would you know if there is a compliant way of writing this without manually creating a `templ.Component` function or writing it manually, so to take advantage of `templ` as a language and do it within the confines of a `.templ` file?

Thanks!

**Comment by filipweidemann** [comment]
Hey there.

I had a similar use case just this morning. Instead of the `style` attribute, I wanted to pass in the `class` attribute to a component from outside.

The markup looks like this:

```go
templ CContainer(attrs templ.Attributes) {
  <div { attrs... }>
    { children... }
  </div>
}
```

and it is called like this:

```go
@components.CContainer(templ.Attributes{"class": "many many tailwind classes here..."}) {
  <span>Content in Container Layout</span>
}
```

The final output will then contain the class attribute with the desired class string. So in your case, all you need to do is to construct some kind of `templ.Attribute` struct in the way you need and pass it as a single argument to your component function.

E.g: `templ.Attributes{"style": "width: 100px;"}`

This behaviour is currently called "spread attributes" and is even more powerful than this. 
Docs: https://templ.guide/syntax-and-usage/attributes/#spread-attributes

Maybe this already helps you? As far as I can tell this should (at least) solve your current use case in your example.

**Comment by thecsw** [comment]
@filipweidemann , thank you! This is a great find. It applies to my case perfectly—will see how to play around with it to make it look real nice as well. Merry Christmas and Happy New Year!
