### ISSUE TITLE
htmx not redirecting after request

### ISSUE THREAD

**Issue by szymon676** [a-h/templ#372]
Hello! I am currently writing application with templ and htmx and I have an issue. 

```html
<button hx-post="/logout" >Logout</button>
 ```
 
```go

func (h *Handler) logout(c *fiber.Ctx) error {
	err := h.sm.Logout(h.sessionid)
	if err != nil {
		log.Error("err while logging out")
		c.Redirect("/profile")
	}
	h.sessionid = ""
	c.Redirect("/login")
	return nil
}
```

after pressing button code executes perfectly fine, entire logic is done right but it is not redirecting to /login

**Comment by szymon676** [comment]
when I try this way however, it is working fine.

```html
<form action="/logout" method="POST"> 
   <button class="text-white bg-gray-800 p-2 rounded outline mt-4" type="submit">Logout</button>
</form>
```

**Comment by a-h** [comment]
According to this stackoverflow question, you may need to add a specific attribute to redirect via a HTMX post.

https://stackoverflow.com/questions/70618200/how-to-implement-a-redirect-with-htmx

I would probably use a standard redirect instead, since logout is a rarely used feature.

**Comment by gungun974** [comment]
> Hello! I am currently writing application with templ and htmx and I have an issue.
> 
> ```
> <button hx-post="/logout" >Logout</button>
> ```
> 
> ```go
> func (h *Handler) logout(c *fiber.Ctx) error {
> 	err := h.sm.Logout(h.sessionid)
> 	if err != nil {
> 		log.Error("err while logging out")
> 		c.Redirect("/profile")
> 	}
> 	h.sessionid = ""
> 	c.Redirect("/login")
> 	return nil
> }
> ```
> 
> after pressing button code executes perfectly fine, entire logic is done right but it is not redirecting to /login

When you use `hx-post`, HTMX never push the URL even when the server return a 301, in fact HTMX, will follow the redirection and replace your element with the HTML response of the redirection.

To solve that you can use `HX-Redirect` but personally I prefer using regular HTML form with `hx-boost="true"` in the form since HTMX will handle your form like the browser would do in AJAX and push the URL and follow the url like the browser would do. (It's more HTML vanilla)

Just don't forget you should not use `hx-boost` and `hx-post` together since `hx-post` is meant to replace an element in the DOM.

Last thing, if you can't use a regular form, (you can't use a form in a form), you can always use `hx-push-url` to push the url
https://htmx.org/attributes/hx-push-url

But don't forget you need to explicit use `hx-target="body"` or you will put your new page into your button ^^
