### ISSUE TITLE
Please elaborate docs about --proxy

### ISSUE THREAD

**Issue by guettli** [a-h/templ#373]
> If the --proxy argument is set, templ will start a HTTP proxy pointed at the given address. The proxy rewrites HTML received from the given address and adds a script just before the </body> tag that will reload the window with JavaScript once the changes are complete and the command has been executed.

Source: https://templ.guide/commands-and-tools/hot-reload#built-in

You explain what --proxy does. But I don't understand the "why?" immediately.

Please elaborate the use-case for the --proxy command.

**Comment by a-h** [comment]
Thanks, I've updated the documentation, and added a diagram, which I think is a good illustration. Feel free to add more to the docs or suggest specific improvements!

**Comment by a-h** [comment]
Docs update live at https://templ.guide/commands-and-tools/hot-reload

**Comment by guettli** [comment]
This command:

templ generate --watch --proxy="http://localhost:8080" --cmd="go run ."

Does it reload if Go code was changed?

I guess it doesn't.

Then I prefer wgo.

I don't create static sites, so the proxy feature is not important for me.

I am very used the use ctrl-r to reload the browser (Stockholm Syndrom?)

The diagram looks good. But to be honest it confused me a bit. 

There are two event sources: file change, and http request arrives.

The initial event is a file change (my pov). The diagram starts with the http request.

If you just want to explain the proxy process, then there should be a corresponding text above the diagram.

But nevertheless thank you for updating the docs.

**Comment by eussam** [comment]
It may be a bit confusing that both `wgo` and `air`are both part of alternate solution of the `hot reload` section of the doc, since none of them does actually implement it (if `hot reload` means automatic reload of the browser page on changes).

However, the doc does state that `air` does not implement a proxy to allow it, maybe the same note should be added to the `wgo` alternate solution.

Basically I understand that both `wgo` and `air` intend to automatically rerun the backend side of a go project, only `templ generate` with the `--watch`, `--proxy` and `--cmd` options <ins>all together</ins> allow a "full" reload (backend and frontend), which is great for me since I don't do much web dev,  therefore not a big fan of CTRL-R 😄 

I guess `hot reload` is the cherry on the cake for web devs, the most important being the automatic rebuilt/restart of the server side. But for it to be really useful it has de respond quickly,  cause it can be counter productive to wait for `hot reload` to happen instead of manually doing it 😄

**Comment by a-h** [comment]
templ's watch mode just got a new capability in https://github.com/a-h/templ/commit/eac495467c1541047facf1ed464088300a9a265a.

In the next release, in `--watch` mode, generated code using `--watch` is different.

In `--watch` mode, templ also generates a file containing all of the markdown and text in the template alongside the Go code, and the generated Go code loads strings from it at runtime.

This means that you don't need to re-compile and restart your application to view text or markdown changes to templates. `templ generate --watch` will update the strings file, and only update the Go file if required. So you can just hit reload (or use the proxy, and the page will be reloaded automatically) and see text or markdown changes.

This should dramatically reduce the amount of times that a full application restart is required in development mode.

I think this is a very interesting change.
