### ISSUE TITLE
JavaScript modules via script tag

### ISSUE THREAD

**Issue by TimVosch** [a-h/templ#394]
To try out Templ, I am porting some Quicktemplate code to Templ. I am using script modules (`<script type="module">`), but I noticed Templ does not seem to support these yet.

At the bottom of this issue is an example of trying to render a graph using uPlot. Note that I am trying to use id parameter in the script, which is just rendering `id` instead of the id. 

How would could this es module scripts be implemented in Templ? The first thing that comes to my mind would be a new directive:

```templ
scriptmodule graph(id) {
        import uPlot from 'https://unpkg.com/uplot@1.6.25/dist/uPlot.esm.js';
        let el = document.getElementById({ id })
}
```

```js
templ IncomeGraph(id string) {
<div class="bg-white rounded drop-shadow p-7 h-[600px] pb-20">
    <div id={ id } class="w-full h-full"></div>
    <script type="module">
        import uPlot from 'https://unpkg.com/uplot@1.6.25/dist/uPlot.esm.js';
        let el = document.getElementById({ id })

        let data = [
            [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
            []
        ]
        data[0] = data[0].map(i => Date.now() / 1000 - (i * 3600 * 24))
        data[0].reverse()
        data[1] = data[0].map((_, i) => Math.sin(i) * 5 + 5)
        const opts = {
            title: "Income",
            width: el.clientWidth,
            height: el.clientHeight,
            series: [
                {},
                {
                    label: "euro",
                    scale: "y",
                    stroke: "red",
                    value: (u, v) => v == null ? null : "€" + v.toFixed(2)
                }
            ],
            axes: [
                {},
                {
                    scale: "y",
                    values: (u, vals, space) => vals.map(v => "€" + v.toFixed(2))
                }
            ],
        }
        let plot = new uPlot(opts, data, el)
    </script>
</div>
}
```

**Comment by a-h** [comment]
Thanks for raising the question. There's some discussion over at https://github.com/a-h/templ/discussions/326 about it too.

In templ, I originally came up with script templates and CSS templates as a way of bundling JavaScript and CSS that is required by a component alongside the markup. The idea is that you should be able to have a Button component, and when you drop it into a page, it also outputs any required CSS or JavaScript. Since you might use the button more than once on a page, templ only outputs that specific CSS or JavaScript once per render operation.

In the case of a module, there's some additional things to discuss. @martinjir raises a question on how it could work.

I think that once we have a design in place, the implementation would be fairly straightforward. I think the main difficulty is understanding the implications of any design, writing it up, and getting community feedback to make sure we don't implement something that turns into a dead end.

**Comment by TimVosch** [comment]
Hey, thanks for the response. I seem to have missed that discussion. I'll have a look at that discussion and see how/where I can help :)
