### ISSUE TITLE
Htmx Attribute Generated as ComponentScript and RenderScriptItems

### ISSUE THREAD

**Issue by rizal111** [a-h/templ#397]
`hx-on::after-request={ "if (event.detail.successful) { return updateTitle(" + nav.Name + ") }" }`

Generated : 
`templ.RenderScriptItems(ctx, templ_7745c5c3_Buffer, "if (event.detail.successful) { return updateTitle("+nav.Name+") }")`

`templ.ComponentScript = "if (event.detail.successful) { return updateTitle(" + nav.Name + ") }"`

other behaviour :
`hx-on::after-request={  }` got compile error `source formatting error: 165:26: expected '==', found '=' `
![image](https://github.com/a-h/templ/assets/61342066/d128e61b-0789-45b4-afd1-7aba2f67d951)

Using  :
VScode
github.com/a-h/templ v0.2.513

**Comment by a-h** [comment]
I think there's two things here:

- 1: the error message isn't very pleasant - it's not obvious why you've got it.
- 2: templ's stopping you from doing this, because it might result in an XSS.

Using `nav.Name` directly in your script via string concatenation could put you at risk of a XSS attack. I'm not sure how the `nav.Name` comes into existence, but if it's user controlled, then a user might be able to name their navigational item as `"") && alert("xss"); //` etc.

In templ, you must use a script component to run that handler code. There's a discussion of how that works at https://github.com/a-h/templ/discussions/228

But specific to your use case, here's an example. I used a before request instead, but note how the `hx-on::before-request` attribute uses a script template.

```templ
package components

script onBeforeRequest(name string) {
	alert("Hello " + name + " from " + event.type + " event");
}

templ Button(id, name string) {
	<div id={ id }></div>
	<button hx-get="/info" hx-target={ "#" + id } hx-on::before-request={ onBeforeRequest(name) }>
		Make request to Adam
	</button>
}

templ Page() {
	<!DOCTYPE html>
	<html>
		<head>
			<script src="https://unpkg.com/htmx.org@1.9.10"></script>
			<title>Buttons</title>
		</head>
		<body>
			<div>
				@Button("id-adam", "Adam")
			</div>
		</body>
	</html>
}
```

Here's the `main.go` file to go with it. It runs the web server, and has the `/info` endpoint that the `hx-get` HTMX attribute works with.

```go
package main

import (
	_ "embed"
	"io"
	"net/http"
	"onclick/components"

	"github.com/a-h/templ"
)

func main() {
	component := components.Page()

	handler := templ.Handler(component)

	http.Handle("/", handler)
	http.HandleFunc("/info", func(w http.ResponseWriter, r *http.Request) {
		io.WriteString(w, "Updated from HTMX request")
	})
	http.ListenAndServe("localhost:8080", nil)
}
```

This gives the following HTML:

```
<html>
   <head>
      <script src="https://unpkg.com/htmx.org@1.9.10"></script>
      <title>Buttons</title>
   </head>
   <body>
      <div>
         <div id="id-adam"></div>
         <script type="text/javascript">function __templ_onBeforeRequest_f1dd(name){alert("Hello " + name + " from " + event.type + " event");}</script>
         <button hx-get="/info" hx-target="#id-adam" hx-on::before-request="__templ_onBeforeRequest_f1dd(&quot;Adam&quot;)">Make request to Adam</button>
      </div>
   </body>
</html>
```

And you can see the following in the browser:

<img width="1033" alt="Screenshot 2024-01-05 at 21 54 25" src="https://github.com/a-h/templ/assets/1029947/8119d392-eaeb-4b15-8033-7cc28ab4eacb">

<img width="855" alt="Screenshot 2024-01-05 at 21 54 33" src="https://github.com/a-h/templ/assets/1029947/f5d063f0-6310-4f0a-8ae7-7c5b050c53e3">

Clearly, this behaviour suprised you, so if you think there's something missing in the docs at https://templ.guide/syntax-and-usage/attributes#javascript-attributes that would make it clearer, and you are able to suggest an improvement to the docs, that would be great.

**Comment by rizal111** [comment]
I get it now. I overlook about javascript attribute. As you mention, a specific error message should helpfull

thanks you very much for your time.
