### ISSUE TITLE
parser: irrelevant error for unterminated strings

### ISSUE THREAD

**Issue by syrm** [a-h/templ#417]
Hello,

I wonder if I'm the only one, but very often the error message isn't very relevant.

One exemple
```go
failed to process path: /app/feature/authentication/register/template/register-last-step.templ source formatting error: 358:57: string literal not terminated (and 10 more errors)
```

templ 
```go
package template

import gt "a/template"
import . "a/service/helper"

templ inputRadio(group string, name string, label string) {
	<div>
		<input type="radio" id={ name } name={ group } value={ name }/>
		<label for={ name }>{ label }</label>
	</div>
}

templ labelInput(name string, label string) {
	<div class={ name }>
		<div>
			<label for={ name }>{ label }</label>
			{ children... }
		</div>
	</div>
}

templ input(name string, inputType string, value string) {
	<input type={ inputType } id={ name } name={ name } required value={ value }/>
}

templ RegisterLastStep() {
	@gt.Layout("main-register-last-step") {
		<form method="post" action="helper.URL(register-submit)">
			<h1>{ T(ctx, "register.create-account-last-step") }</h1>
			<input type="hidden" name="login" value="form.Login"/>
			<input type="hidden" name="password" value="form.Password"/>
			@labelInput("birth-year", "année de naissance") {
				@input("birth-year", "number", "1982")
			}
			@labelInput("gender", "genre") {
				@inputRadio("gender", "female", "féminin)
				@inputRadio("gender", "male", "masculin")
			}
			<div class="submit">
				<button type="submit">{ T(ctx, "register.register") }</button>
			</div>
		</form>
	}
}
```
(missing " after féminin)

**Comment by joerdav** [comment]
Hi @syrm thanks for raising this!

What about the error do you find to be irrelevant? To me it points quite nicely to the issue that `string literal not terminated`

**Comment by syrm** [comment]
`error: 36: string literal not terminated`
this error is at line 36 not 358:57

**Comment by a-h** [comment]
I ran into the cause of this bug recently, and fixed it upstream in https://github.com/a-h/parse/commit/3caf7543159ac718932c2364342fa25ef6edfcc1

I'm working on a rewrite of the parser logic in https://github.com/a-h/templ/tree/go_ast_v2 which bumps the parser version and will resolve this.

The new parser logic uses the Go AST parser to parse Go code instead of relying on heuristics like matching `for <go code> {\n` to find Go expressions. It will enable multi-line string expressions, for statements, etc. and pave the way for arbitrary Go statements in templ too, e.g. (`{{ x := calculateOnce() }}`.

**Comment by joerdav** [comment]
@syrm with the mainline version of templ there should be a more relevant error. Feel free to re-open if this is not resolved as expected.

**Comment by a-h** [comment]
Yes, thanks @joerdav - the fix should have been merged in https://github.com/a-h/templ/commit/3de67f6fc73dafd1b5123d393044864c1c56fad1
