### ISSUE TITLE
cmd: clean up generate stdout/stderr

### ISSUE THREAD

**Issue by egtann** [a-h/templ#439]
First off, thank you for this amazing tool. I am loving the experience with templ so far! I do have some small ideas which would improve quality of life when using `templ generate`.

There's two small improvements to the UX of the CLI tool that we can make:

### 1, stdout
Each time `templ generate` runs, it sends a very large amount of text to stdout on success. This is at odds with how most Unix and Go tools work, since those generate no output on success. Ideally `templ generate` would behave like other tools and not output hundreds of lines on every build in a large project, as this effectively wipes my terminal on each run given how many lines it outputs.

If we want to output debug information like how long every file took to generate, that should be under a verbose flag.

To work around this, I've started using `templ generate 1>/dev/null` in a Makefile, but this leads me to my next issue.

### 2. stderr
Failures/errors are outputted to stdout, so when I get an error, if I'm discarding the noise from stdout, I get no output or an unhelpful error:

```
$ templ generate 1>/dev/null
# <there's no output if it errors>

$ make templ
make: *** [Makefile:2: templ] Error 1
```

**Comment by a-h** [comment]
I've introduced a new structured logger, with a custom colourised handler in https://github.com/a-h/templ/pull/470 while I was rewriting everything.

I thought that a fancy TUI was overkill once the output was tidied up. By default, it logs at `Info` level, so the default output is much simpler, just providing a summary.

```
$ templ generate
(✓) Complete [ updates=54 duration=87.295806ms ]
```

It's now under a verbose flag. You can set `-v` for debug mode, or set the level to "warn", "error" etc.. with the `-log-level` flag if you want no output at all unless there's errors.

However, I've kept the logs on stdout, since go's slog handler only has the choice of one and the logs *are* the program output.

**Comment by a-h** [comment]
Update on this one. Decided to log to `stderr`, since it affects Bazel and other users to log to `stdout`.

https://github.com/a-h/templ/issues/753
