### ISSUE TITLE
scripts: js minify

### ISSUE THREAD

**Issue by maltegrosse** [a-h/templ#500]
first of all, amazing tool!

is it possible to implement some minify tools, especially regarding the javascript code. Seems like a good go library exists:
https://github.com/tdewolff/minify

**Comment by stephenafamo** [comment]
If this is to be considered, I think esbuild may be a better tool to rely on.

**Comment by nathan-hello** [comment]
You could use your favorite javascript minifier in a build step, and point your <script> tags to the foo.min.js file instead of foo.js.

**Comment by joerdav** [comment]
Currently the only way to achieve this would be to ditch templ `script`s and create your own JS files that are minified and referenced by your templates.

I think that the code in templ scripts should be small so may not really benefit from minification, which I believe is ideal for projects with large JS assets which are usually inflated by dependencies.

**Comment by stephenafamo** [comment]
It would also be great if templ's LSP can perhaps also proxy to another LSP for JS (similar to how Go code is checked with `gopls`)

**Comment by a-h** [comment]
That is also something that I'm looking at @stephenafamo - I put an example of what that could look like at https://github.com/a-h/templ/issues/498#issuecomment-1937716137

The example demonstrates the concept of being able to have just the HTML rendered, which would massively simplify the use of HTML and other LSPs.

**Comment by tommyo** [comment]
I think the same applies to css. Being able to run the component level css through postcss at generate time opens up a whole ecosystem of plugins without templ having to be aware.

So maybe a hook/middleware in the generate logic that calls out to plugins, allowing custom logic?

Alternatively, a vite plugin that triggers `templ generate` so that vite handles the esbuild, postcss and bundling. I think that may even help the LSP.

I'm going to dig around under the hood today and see what that would take.

**Comment by joerdav** [comment]
Due to the [recommendation](https://templ.guide/syntax-and-usage/script-templates#script-templates) to move away from script templates I think we can close this.

The decision is due to scenarios exactly like this, we cannot support all of the workflows that people like to process js and css, so making the interop with the outputs of said processes should be the priority.

**Comment by phanirithvij** [comment]
It's not recommended to pass go values to scripts anymore?
The alternative then is to have an API endpoint and a fetch call in the js?
Aren't we losing a very useful feature?
