### ISSUE TITLE
Cannot render in Docker

### ISSUE THREAD

**Issue by IcelandicIcecream** [a-h/templ#510]
Hey guys, I have a server running with templ & echo, it works locally but not when I build it with docker. Here's my dockerfile:

```
handlers.go: ----------------------------------------------------------------------------------------------------------------------------------------------------

package handlers

import (
	"github.com/a-h/templ"
	"github.com/icelandicicecream/ben-portfolio-v2/model"
	"github.com/icelandicicecream/ben-portfolio-v2/views/components"
	home "github.com/icelandicicecream/ben-portfolio-v2/views/pages/home"
	"github.com/labstack/echo/v4"
)

type Handler struct {
	state model.State
}

func (h Handler) Home(c echo.Context) error {
	return Render(c, home.Home(h.state))
}

func (h Handler) OpenMobileNavbar(c echo.Context) error {
	return Render(c, components.MobileNavBar())
}

func (h Handler) CheckHealth(c echo.Context) error {
	return c.String(200, "The echo server is up and running! 🚀")
}

func Render(c echo.Context, t templ.Component) error {
	c.Response().Header().Set(echo.HeaderContentType, echo.MIMETextHTML)
	return t.Render(c.Request().Context(), c.Response().Writer)
}


Dockerfile: --------------------------------------------------------------------------------------------------------------------------------------------------------

FROM golang:latest AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . /app

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/app/main.go

FROM alpine:latest

RUN apk add --no-cache bash

WORKDIR /app

COPY --from=build-stage /app/main .
COPY --from=build-stage /app/styles ./styles
COPY --from=build-stage /app/assets ./assets
COPY --from=build-stage /app/.env .

EXPOSE 8080

CMD ["./main"]
```

I'm not too sure what's happening, it gives me an internal server error when I navigate but my middleware is logging out 200. /check-health works just fine when I access it since it's not rendering any html

**Comment by IcelandicIcecream** [comment]
Adding to this:
Here's the error I'm getting: 2024-02-09T17:08:46Z ERR server/server.go:23 > 200 | GET: '/' -- templ: failed to cache strings: templ: failed to open /app/views/layout/base_templ.txt: open /app/views/layout/base_templ.txt: no such file or directory pid=1

**Comment by IcelandicIcecream** [comment]
> Before the build step in Docker you need to run `temple generate` it's copying over your `--watch` mode templates.

Oh I see. So I would need to build and install templ in my docker image, and then ```templ generate``` to get the txt files during my build stage? Is this the best way? seems a bit excessive haha Also, for some reason, when I do templ generate.. It doesn't generate the txt files anymore. Only templ generate --watch does and it deletes the txt file when I stop it

**Comment by joerdav** [comment]
The txt files are only relevant for dev mode. When you run templ generate on it's own you get the production templates. That's why I'd recommend a templ generate in your build process, just incase you forgot to do a prod build.

**Comment by alehechka** [comment]
> So I would need to build and install templ in my docker image, and then `templ generate` to get the txt files during my build stage? Is this the best way? seems a bit excessive

I feel like it's better to do it this way imo. When I use templ I gitignore all of the Go code that templ generates (all `*_templ.go` files) and the docker image runs `templ generate` everytime so it always has the most up-to-date code. This also will fail the docker build if templ throws an error during generation which is better because it ensures the templ code I pushed is still valid.

Here's an snippet from one of my projects:
```dockerfile
# BASE IMAGES
FROM --platform=$BUILDPLATFORM golang:1.21 as go-base

# GENERATE TEMPL

FROM go-base as templ-builder

WORKDIR /app

COPY go.mod .
COPY Makefile .

# install templ version that go.mod is using
RUN go install github.com/a-h/templ/cmd/templ@$(go list -m -f '{{ .Version }}' github.com/a-h/templ)

COPY web/templ web/templ

RUN templ generate --path=web/templ
```

**Comment by IcelandicIcecream** [comment]
> > So I would need to build and install templ in my docker image, and then `templ generate` to get the txt files during my build stage? Is this the best way? seems a bit excessive
> 
> I feel like it's better to do it this way imo. When I personally use templ I gitignore all of the Go code that templ generates (all `*_templ.go` files) and the docker image runs `templ generate` everytime so it always has the most up-to-date code. This also will fail the docker build if templ throws an error during generation which is better because it ensures the templ code I pushed is still valid.
> 
> Here's an snippet from one of my projects:
> 
> ```dockerfile
> # BASE IMAGES
> FROM --platform=$BUILDPLATFORM golang:1.21 as go-base
> 
> # GENERATE TEMPL
> 
> FROM go-base as templ-builder
> 
> WORKDIR /app
> 
> COPY go.mod .
> 
> # install templ version that go.mod is using
> RUN go install github.com/a-h/templ/cmd/templ@$(go list -m -f '{{ .Version }}' github.com/a-h/templ)
> 
> COPY web/templ web/templ
> 
> RUN templ generate --path=web/templ
> ```

Awesome thanks for this, I'll use it as a reference for mine. Having thought about it, it does make sense to do it on build to simplify the CI/CD process

**Comment by adasauce** [comment]
Just a little inquiry on this, the error failing explicitly says "failed to cache strings", and it looks like that's being generated by `WriteWatchModeString`

```
// WriteWatchModeString is used when rendering templates in development mode.
// the generator would have written non-go code to the _templ.txt file, which
// is then read by this function and written to the output.
```

based on the documentation, this shouldn't be getting called at all, right? this isn't dev mode -- it's likely production.

is the documentation misleading, or is this function getting called accidentally?

especially given an app is probably running in a hardened container, it shouldn't be writing anything out to the filesystem (and in many cases doesn't have permission to at all).

**Comment by adasauce** [comment]
oh, I think I missed something re-reading this thread. If I check in the generated go code from when templ was running in watch mode it's going to make reference to this function.

I had checked it in from a previous issue I was reading mentioning it was idiomatic to commit the generated code so that people who don't have the templ built tools installed ahead of time can build the application without worrying about that step of the build chain.

**Comment by andersryanc** [comment]
What is the purpose of the text files when developing locally? Seems like it adds more complications than benefit. For instance, even if you choose to gitignore them AND also decide to take the idiomatic approach to track the generated go files, it would be very easy during development to stage and commit all your files to git (in the middle of your work) without first stopping the `templ generate --watch` command. This would then lead to a problem state where the generated go files you committed are referencing the txt files you chose to ignore...

In my opinion @alehechka has a good point to ignore them both and run the generate command in the CI/CD (or manual build) process. It's not as convenient as @adasauce points out, but if someone is building and running the app for development, they will probably need to install templ cli at some point anyways right?

Lastly, I think it would be helpful to update the docs on the website to discuss gitignore and deployment best practices more clearly. I ended up on this issue because I could not find a mention of if the generated text files should be tracked or not in the repository. I looked at the [docker example](https://github.com/a-h/templ/tree/main/examples/counter-basic) also and noticed that the generated go files are tracked and that is also does not have a .gitignore file at all.
