### ISSUE TITLE
propsal: storybook - allow importing of additional resources such as css.

### ISSUE THREAD

**Issue by joerdav** [a-h/templ#53]
I'm working on a component library for tailwindcss, but I think there's some missing functionaility in the storybook package.

To import css into storybook I would need an easy way to add scipts/stylesheets to storybook.

This can be done via the preview-head.html file I believe. <https://storybook.js.org/docs/react/configure/story-rendering#adding-to-&#60head&#62>

**Comment by bastianwegge** [comment]
@joerdav sorry to tag you here, but did you end up writing a component library for tailwind? Maybe one that you'd even be willing to share?

**Comment by joerdav** [comment]
Sorry I didn't @bastianwegge , I later realized that a component library isn't really the right use for tailwind. The tailwind lsp is probably the best tooling to build things with templ and tailwind.

There could be a use for a Go way of generating tailwind classes, but even then, it could be argued that it would be needless abstraction.

**Comment by bastianwegge** [comment]
I have created a table and a universal form component, both with managable viewModels that we use them for abstraction inside of our projects. I'm in the midst of creating a reusable library, that's why I was asking. I have also seen the "storybook" example inside the repo but it didn't work when I was testing it. If this topic comes up again, feel free to reach out.

In any case: Thanks for the quick reply, hope you have a great day.
