### ISSUE TITLE
Docker Image Creation on Release

### ISSUE THREAD

**Issue by alehechka** [a-h/templ#564]
# Overview
I wanted to pitch the idea of creating an official Docker image published to DockerHub/GitHub Container Registry as an additional means to run templ commands via docker container and/or be able to use the image as a build step in our own docker images.

In my local development I like to use docker-compose to quickly spin up containers for each of my file watching processes (templ, tailwind, air) and have them all connected with the proper volumes. Since templ does not have an official docker image I've just been using the default Go image and installing templ on to it. This has been completely fine thus far and the Dockerfile is very [minimal](https://github.com/alehechka/dqix/blob/main/.docker/Dockerfile.templ), but I thought it would be great to have an official one that comes with templ already installed.

The latter use case is also from a personal workflow in which I generate all templ Go code on build within a [Dockerfile](https://github.com/alehechka/dqix/blob/987055ffa04251f7da6d11d5e2c2c60713d67633/Dockerfile#L24-L36). This is also very simple setup, but would be able to further benefit from a pre-packaged image.

Let me know what you think.

**Comment by a-h** [comment]
I'm up for having a Docker container for templ.

templ uses goreleaser for releases. There's support for building and pushing Docker containers in that. https://goreleaser.com/customization/docker/#how-it-works

I'd prefer to build Docker containers from Nix though.

Github has a built-in container registry, so it's straightforward to push containers.

I manually execute releases at the moment, so that I can digitally sign them with a hardware security token, but could move to using Github Actions to do the release build.

**Comment by a-h** [comment]
This is no fun at all. I've spent about 2 hours messing about with Github Workflows.

https://github.com/a-h/templ/blob/main/.github/workflows/release.yml and https://github.com/a-h/templ/blob/main/.goreleaser.yaml

Running into permissions issues pushing to Github.
