### ISSUE TITLE
bug: backslashes in constant string attributes cannot be generated

### ISSUE THREAD

**Issue by zmzlois** [a-h/templ#624]
This issue is circling back to to https://github.com/a-h/templ/issues/498

On top of Lsp support, HTML's input element has a built in attribute [pattern](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern) which:
- allows us to validate user's input in the browser with regular expression
- custom error message on input field with [setCustomValidity](https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/setCustomValidity)

Previously I had a case of validating url links and this pattern `(https?|ftp):\/\/[^\s/$.?#].[^\s]*` worked in javascript, but it doesn't work in templ or Golang (tried passing it from backend as a string). templ lsp and parser will warn me with a red flag and causing generation failure at `\s`. 

The alternative of not having this feature is either use additional javascript + bundle to add input validation or using [validation from htmx](https://htmx.org/docs/#validation) where the lsp + syntax highlighting features are not yet complete.

**Comment by a-h** [comment]
Please provide a reproducible example, with instructions of what to run, and explain what you expect to happen, and what is actually happening.

**Comment by zmzlois** [comment]
so in the repo https://github.com/zmzlois/templ-repro I have provided two example, where regular expression is working in `test.ts` , but it will cause parsing failure in templ

**Comment by joerdav** [comment]
I understand the issue. This isn't related directly to regex but how we represent string attributes.

In HTML, this is a valid attribute: `pattern="/^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$/i"`
Or a minimal reprod, this is valid HTML too: `pattern="\s"`

HTML spec states that an attribute value can contain anything except for a `"` or a `&`. So an unescaped `\` is in-fact valid. But, we generate these strings directly to Go strings without escaping, where a backslash on it's own is invalid.

So I believe that the solution here, is to Go string escape constant string attributes(replace `\` with `\\`). We shouldn't change the behaviour of expressions, since they are go strings, and follow go escaping rules.

**Comment by Robert-Kolmos** [comment]
Hey all, I'd like to take a crack at this one.

**Comment by a-h** [comment]
Nice. I'd love a PR on it. Crack on mate! 😀 

If you don't have time, just say, and I'll get to it.

**Comment by Robert-Kolmos** [comment]
Question for the group here. If we start escaping constant string attributes I believe that will be a breaking change because someone previously could have done
```
templ input() {
    <input pattern="\\s" /> 
}
```
which would have resulted in `<input pattern="\s">`. With escaping this would become `<input pattern="\\s">`

I've got a [commit here](https://github.com/a-h/templ/compare/main...Robert-Kolmos:templ:escaping-repro) that demonstrates how to make the current state of the project generate the `(https?|ftp):\/\/[^\s/$.?#].[^\s]*` pattern from the start of this thread.

Do we want to avoid making users do this sort of escaping, and if so should I put this behavior behind a flag and default to the old behavior?

**Comment by joerdav** [comment]
I think we want to avoid making users use backticks. Someone should be able to copy/paste HTML without amendments into a templ file.
