### ISSUE TITLE
question: How to handle conditional html attributes and self closing tags

### ISSUE THREAD

**Issue by nics** [a-h/templ#65]
Hi,

I have a question about tag building. The parser errors on fragments like these:

```
 <button class="close" type="button" aria-label="Close" data-dismiss="toast"
     if f.DismissAfter > 0 {
          data-delay={ f.DismissAfter.Milliseconds }
     } else {
          data-autohide="false"
     }
  >
      <i class="if if-close"></i>
  </button>
```

What is the best approach to tag building or handling optional attributes?

I also get parse errors with html 5 self closing tags like `link` and `img` if I don't add closing slashes. Is this intentional behaviour? 

Thanks for a very promising looking project!

**Comment by a-h** [comment]
Great question! There's currently no way to selectively add/remove attributes at render time.

To solve your immediate need, you could implement a custom `templ.Component` in code that dynamically renders the attributes.

To use it would look like this.

### page.templ

```templ
package main

templ page(props PageProps) {
	<html>
		<head><title>{ props.Title }</title></head>
		<body>
			@ToastCloseButton(props.DismissAfter) {
				<i class="if if-close"></i>
			}
		</body>
	</html>
}
```

### main.go

All the code in this example can be put in one file, I've just broken it up to explain it.

In `templ`, anything that implements the `templ.Component` interface is a component. So we can implement a `RuntimeElement` component.

Instead of being compiled down to source code, it chooses which attributes to write out at runtime. The performance of this would be slightly less than doing it at compile time, but still good. I've slipped the many `if err != nil` checks here and a bit of performance optimisation that the library uses itself, which is to check whether it was passed a `bytes.Buffer` and use it directly instead of the `io.Writer` interface.

```go
type RuntimeElement struct {
	Name       string
	Attributes map[string]any
}

func (re RuntimeElement) Render(ctx context.Context, w io.Writer) error {
	io.WriteString(w, "<")
	io.WriteString(w, re.Name)
	if len(re.Attributes) > 0 {
		io.WriteString(w, " ")
		var keys []string
		for k := range re.Attributes {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			v := re.Attributes[k]
			io.WriteString(w, html.EscapeString(k))
			io.WriteString(w, "=")
			io.WriteString(w, attributeValue(v))
		}
	}
	io.WriteString(w, ">")
	if c := templ.GetChildren(ctx); c != nil {
		c.Render(ctx, w)
	}
	io.WriteString(w, "</")
	io.WriteString(w, re.Name)
	io.WriteString(w, ">")
	return nil
}

func attributeValue(v any) string {
	switch v := v.(type) {
	case string:
		return fmt.Sprintf("%q", html.EscapeString(v))
	case int:
		return fmt.Sprintf(`"%d"`, v)
	case int32:
		return fmt.Sprintf(`"%d"`, v)
	case int64:
		return fmt.Sprintf(`"%d"`, v)
	case float64:
		return fmt.Sprintf(`"%f"`, v)
	case bool:
		return fmt.Sprintf(`%v`, v)
	default:
		//TODO: You'd want to log this.
		panic(fmt.Sprintf("unsupported attribute value type: %t", v))
	}
}
```

A `ToastClose` component can then be defined that uses it.

```go
func ToastCloseButton(dismissAfter time.Duration) templ.Component {
	e := RuntimeElement{
		Name: "button",
		Attributes: map[string]any{
			"class":        "close",
			"type":         "button",
			"aria-label":   "Close",
			"data-dismiss": "toast",
		},
	}
	if dismissAfter > 0 {
		e.Attributes["data-delay"] = dismissAfter.Milliseconds()
	} else {
		e.Attributes["data-autohide"] = "false"
	}
	return e
}
```

To test what it renders, I put in a test webserver and created PageHandler that calls the `page` function defined in the templ file.

```go
func main() {
	http.Handle("/", PageHandler{})

	// Start the server.
	fmt.Println("listening on http://localhost:8000")
	http.ListenAndServe("localhost:8000", nil)
}

type PageHandler struct{}

func (ph PageHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	props := PageProps{Title: "Test example", DismissAfter: time.Second}
	templ.Handler(page(props)).ServeHTTP(w, r)
}

type PageProps struct {
	Title        string
	DismissAfter time.Duration
}
```

**Comment by a-h** [comment]
To handle this scenario in the longer term, I could update the templ syntax to allow for a new attribute called `attrs` which accepts either a string (for compatibility in case someone has ever used an attribute in the past called `attrs`), or an expression which must return an array of `templ.ElementAttribute` values to append to the attributes at render time.

```go
func getButtonAttributes(pp PageProps) (attrs []templ.ElementAttributeValue) {
	if pp.DismissAfter > 0 {
		return append(attrs, templ.NewElementAttributeValue("data-delay", pp.DismissAfter.Milliseconds())
	}
        return append(attrs, templ.NewElementAttributeValue("data-autohide", "false")
}

```templ
<button class="close" type="button" attrs={ getButtonAttributes(props) } />
```

Would love your thoughts on that!

**Comment by a-h** [comment]
Finally, you asked about the closing `/` on elements. It *is* required by templ's parser (same as JSX), but when templ renders HTML, it's aware of the void elements as per the HTML 5 spec and renders them without...

So, `<img src="images/test.png"/>` in templ will render `<img src="images/test.png">`.

In the code it's here: https://github.com/a-h/templ/blob/main/generator/generator.go#L727-L732C2 and goes through to https://github.com/a-h/templ/blob/3c693671ddf8c025b7bb70765d3ad5d1804c95a5/parser/v2/types.go#L312-L319

**Comment by joerdav** [comment]
This doesn’t solve the classes issue, but how about a new bit of templ syntax:

```go
<button 
    class="close" 
    type="button" 
    data-delay(pp.DismissAfter > 0)={pp.DismissAfter.Milliseconds()} 
    data-autohide(pp.DismissAfter <= 0)="false" 
/>
```
Obviously just a first draft of the syntax, but the gist is that you have somewhere to shove a bool expression.
The issue with this is that if there are multiple attributes driven by the same bool, it could get repetetive.

**Comment by nics** [comment]
Hi,

thanks for all the responses.

I'm new to this, but a bit of extra syntax to handle simple cases like in @joerdav's example  seems like a good idea (like what is done with boolean html attributes). More complex cases are probably a smell or can be handled by a component.

More interpolation literals could probably also make the language more expressive? Currently there is only `{ }` and `{! }`.
Things that come to mind:

- `{s }`: Stringify the output (numbers , bools)
- `{? }`: Only add the output  if it is truthy

These could follow the semantics of the stdlib html/template package.

If your thinking goes more towards pseudo attributes like in @a-h's `attrs={ }` example above, It's probably a good idea to prefix them with `templ-` similar to how hotwired and htmx prefix their html attributes?

**Comment by joerdav** [comment]
In terms of more interpolation literals, it could help in this case. However I think in the case of Stringify, it's trivial to stringify in Go, so is clearer I think to just do `{fmt.Sprint(myString)}`. And in the case of "truthy" that will be tough, because which values in Go are "truthy"?

**Comment by a-h** [comment]
Thinking about this some more, I think that what you originally wrote might be the best way. It's what you wrote naturally, and assumed would work. Looking at it, I think it should work too.

```html
 <button class="close" type="button" aria-label="Close" data-dismiss="toast"
     if f.DismissAfter > 0 {
          data-delay={ f.DismissAfter.Milliseconds }
     } else {
          data-autohide="false"
     }
  >
      <i class="if if-close"></i>
  </button>
```

**Comment by a-h** [comment]
Just landed a big refactor to the parser at https://github.com/a-h/templ/commit/c009aa0cd2924af90b63800d22dc4b6125675b03, which I wanted to tackle before getting onto this.

It migrates to a new parser library I wrote (https://github.com/a-h/parse) to replace my previous one (https://github.com/a-h/lexical). The new library uses generics which makes the code a lot tidier - the result is that the parser code is about 10% smaller overall, now at 6500 lines of Go code from 7100.

To add this new functionality, I'll need to target the attribute parser to add a new type of attribute (`ConditionalAttribute`) that looks like the `If` statement, but only supports having attributes as its children (you can't drop in a HTML node).

It should be a case of updating this code: 
https://github.com/a-h/templ/blob/8072edc309853d5adad1fdedb1f0e474701ef56e/parser/v2/elementparser.go#L242-L261

And using a variation of this `If` parser: https://github.com/a-h/templ/blob/main/parser/v2/ifexpressionparser.go - instead of using the template node parser, it will look for attribute values instead.

Then, I'll need to update the generator to generate code to support that, and check that formatter renders out the changes correctly.

In terms of supporting `for` and `switch` statements, variable assignments etc., I don't think that's in scope for this change.

**Comment by a-h** [comment]
I've added a new parser to this branch https://github.com/a-h/templ/tree/add_conditional_attribute in this commit https://github.com/a-h/templ/commit/c57755bc769a29ffeac923c87d85201e67757047

The commit adds the capability to support `if` statements in the element attribute set.

```templ
<hr style="padding: 10px" 
			if true {
				class="itIsTrue"
			}
/>
```

The next task is to update the Go code generator to generate `if` statements in the generated code, and to create tests that test the code that is generated from the templ output.

**Comment by a-h** [comment]
It wasn't difficult to update the generator to add conditional expression support. I've done that in the `add_conditional_attribute` branch in https://github.com/a-h/templ/commit/aff6675ecc553b6a9f6addbda8c78995d700b815

@nics - if you care to build that branch and test it, it should be exactly the syntax you initially tried. What do you think?

The next task would be additional testing, and I think the auto-formatting needs a little improvement.
