### ISSUE TITLE
Proposal: Change URL's signature to match [S]Printf

### ISSUE THREAD

**Issue by emehrkay** [a-h/templ#798]
Go from:

```go
func URL(s string) SafeURL {
```

To:

```go
func URL(format string, a ...any) SafeURL {
   s := fmt.Sprintf(format, a...)
```

This would be a backwards compatible change and would save some function nesting in templ funcs

**Comment by a-h** [comment]
I like the idea of having a url format / builder function.

If it was the signature of `Sprintf`, e.g.: `urlf.Sprintf("/path/%s/fileName.js?%s=%v", "pathvar/", "qkey?", "&other=true")` there's a few dangers to consider... Because of the context of the variable substitution, there's a risk of injection attacks, so the values would need to be appropriately escaped:

* path variables need to be path escaped so that `/` etc. is encoded.
* query variables need to be query escaped so that `?`, `=` etc. are properly encoded.

There's also the question of what happens if you do something like:

```go
urlf.Sprintf("?%s", "data")
```

It could live in `github.com/a-h/templ/urlf` to avoid the name of oddity of `templ.URLf` or similar, but I don't mind `templ.URL`

I wonder if a builder style is better, since it turns issues with `sprintf` replacement into compile time issues:

```go
urlbuilder.Build().Path("a").Path("b").Path(c).Query(key, value)
```

**Comment by joerdav** [comment]
There could be an unsafe counterpart too, `urlf.UnsafeSprintf`.

**Comment by a-h** [comment]
I think the next action is to track usage of the package. If it's used a lot, then we merge it into the mainline.

This is where Github needs a "remind me in 6 months" function. 😁 

Good ideas always come back, so I'll close for now to keep the issues list as manageable as we can.
