### ISSUE TITLE
proposal: Cache-bust Static Assets

### ISSUE THREAD

**Issue by x80486** [a-h/templ#804]
Static assets are usually cached for optimal performance. However, when they are updated, there is a risk the browser or CDN serves up the stale, cached version instead of the new one.

_Cache-busting_ is a technique to avoid this happening.

`templ` could implement a feature to wrap the resource links in the markup, if/when specified, with a function that provides this behavior. For instance, instead of using `href="/styles/global.css"`, it could be something like `href=templ.ResourceLink("/styles/global.css")`.

A hash to the linked path in the markup is generated, so a stale cached version never gets served; e.g.: `http://localhost:8000/favicon.svg?__templ_c=7dce7a2cff78e87ab6c0cc0bc7b75b67092b9725`.

**Comment by joerdav** [comment]
Hey! Interesting proposal!

Do you have any kind of thoughts on what the `ResourceLink` function would look like?

And a follow up on that, do we think this would be widely used enough that we want to support it in the templ codebase (@a-h might have some thoughts on this), or maybe it could be a function that we document that people can copy into their own projects?

**Comment by x80486** [comment]
> Do you have any kind of thoughts on what the `ResourceLink` function would look like?

I think the safest path is to read the resource represented by the provided link and compute its hash. In that case, the mechanism will only use a new value if the are indeed changes within the file.

I'm not clear if this would change between operating systems. If that's the case, another approach should be taken, otherwise people with different operating systems are going to generate new values just by generating the templates — since these are usually not generated in a continuous integration environment, but delivered along with the source code.

> And a follow up on that, do we think this would be widely used enough that we want to support it in the templ codebase (@a-h might have some thoughts on this), or maybe it could be a function that we document that people can copy into their own projects?

It depends on the scope of the project. It looks very much like something you could have —even more since it should be really simple—, but you can draw the line on the other side as well. The way I see it is: this is part of the generated HTML.

**Comment by a-h** [comment]
I think this sort of thing would be better implemented before compile time. For example, if you had a directory that you knew you were serving up, you could write a script to auto-generate a file that contained a map of the URL to the SHA256 hash.

```go
urlToHash := map[string]string{
  "/styles/global.css": "7dce7a2cff78e87ab6c0cc0bc7b75b67092b9725",
}
```

Then, your `resourceWithHash` function would be:

```go
func resourceWithHash(url string) string {
	hash, hasHash := urlToHash[url]
	if !hasHash {
		return url
	}
	// TODO: Parse the URL and adapt the querystring instead of concat.
	return url + "?__templ_c=" + hash
}
```

So long as you're not making changes to static assets without redeploying your app, you're good to go. But if you are, you could store the contents of the `urlToHash` map in a JSON file that you store alongside the static assets, and get your app to download and update the in-memory map every few minutes.

Clearly, you wouldn't want to calculate the hash of the file on every request, since it's a waste of CPU.

Setting proper cache headers is also worth doing, e.g. https://medium.com/pixelpoint/best-practices-for-cache-control-settings-for-your-website-ff262b38c5a2

**Comment by joerdav** [comment]
Another possibility would be to use some metadata of your app as the cache value. This would similarly only work if your app was deployed all as one. And may involve cache busting when there are no changes to an asset. 

```go
func resourceWithHash(url string) string {
	bi, ok := debug.ReadBuildInfo()
	if !ok {
		return url
	}
	// TODO: Parse the URL and adapt the querystring instead of concat.
	return url + "?__templ_c=" + bi.Main.Version
}
```

**Comment by a-h** [comment]
# Calculating file versions

If you include a file version in the querystring, and set `Cache-Control` headers, the browser will only fetch new versions.

@joerdav's solution works great for that (although the code would need to parse into an `url.URL`, and modify the querystring, since the URL might already have query values), but means that every new software release causes all the files to be re-downloaded by browsers.

# Pre-calculating file versions

Pre-calculating file versions instead, and turning them into a map, would mean that the files don't get re-downloaded unless changed, but requires some pre-work.

Some talk about this here: https://www.reddit.com/r/golang/comments/118pqb2/cache_headers_when_serving_embedded_files/

# Etag

To preventing the browser from re-fetching the full file if there aren't any changes, you can use cache-control and etag headers. The etag specifies the hash of the file, and can be calculated by simple middleware, see https://rednafi.com/misc/etag_and_http_caching/ for a starting position.

But... means that the server does some work at runtime to calculate the hash of files, and browsers will also still check for new versions from time to time.

# Summary for templ

I think it's out of templ's scope to deal with this, but my research showed that maybe there's a gap in the market for caching middleware.

**Comment by a-h** [comment]
By the way, @x80486 - you mentioned you're using Fiber, which has etag middleware already: https://docs.gofiber.io/api/middleware/etag/

A lot of commercial projects would have a CDN like CloudFlare or CloudFront which will take load away from the origin server once an initial etag is provided.

I don't think there's any action for the templ project to take here, except the possibility of documenting solutions to caching, which isn't really specific to templ, but templ is attracting people who haven't built web apps before, so I don't mind filling the information and help void.

I think the conversation has closed, because it hasn't moved since June, but feel free to re-open.
